Repository jolibrain/deepdetect, pull requests merged in 2018-10, with the labels that each got.

#503 Retrieve files from subdirectories of class directories
  src/backends/caffe/caffeinputconns.cc
  src/backends/caffe/caffemodel.cc
  src/backends/caffe2/caffe2inputimg.cc
  src/backends/caffe2/caffe2model.cc
  src/backends/dlib/dlibmodel.cc
  src/backends/tf/tfmodel.cc
  src/backends/xgb/xgbmodel.cc
  src/imginputfileconn.h
  src/txtinputfileconn.cc
  src/utils/fileops.hpp
Labels: connectors, images

#511 tsne can now send the number of iterations
  src/backends/tsne/tsnelib.cc
Labels: enhancement

#512 Add USE_CAFFE_DEBUG flag
  CMakeLists.txt
Labels: compilation

#514 added ability to avoid index preloading
  src/mlmodel.h
  src/simsearch.h
Labels: API, C++, filesystem, simsearch

#504 Train images models from txt files
  src/backends/caffe/caffeinputconns.cc
  src/backends/caffe/caffeinputconns.h
Labels: connectors, images
