Repository jolibrain/deepdetect, pull requests merged in 2018-12, with the labels that each got.

#525 correct logic for benching rois: do not ask for bbox, rois does bbox …
  clients/python/dd_bench.py
Labels: bug

#507 Added mask support for detectron models
  CMakeLists.txt
  examples/caffe2/detectron/README.md
  examples/caffe2/detectron/convert_pkl_to_mask_net.py
  examples/caffe2/detectron/generate_coco_corresp_file.py
  examples/caffe2/detectron/masks.md
  examples/caffe2/detectron/plot_masks.py
  patches/caffe2/collect_proposals.patch
  patches/caffe2/custom_ops/bbox_to_roi_op.cc
  patches/caffe2/custom_ops/bbox_to_roi_op.h
  patches/caffe2/custom_ops/multi_level_roi_op.cc
  patches/caffe2/custom_ops/multi_level_roi_op.h
  patches/caffe2/custom_ops/segment_mask_op.cc
  patches/caffe2/custom_ops/segment_mask_op.h
  src/CMakeLists.txt
  src/backends/caffe2/caffe2inputimg.cc
  src/backends/caffe2/caffe2lib.cc
  src/backends/caffe2/caffe2lib.h
  src/backends/caffe2/caffe2libstate.h
  src/backends/caffe2/caffe2model.cc
  src/backends/caffe2/caffe2model.h
  src/backends/caffe2/nettools.h
  src/backends/caffe2/nettools/debug.cc
  src/backends/caffe2/nettools/devices_and_operators.cc
  src/backends/caffe2/nettools/netgroup.cc
  src/backends/caffe2/nettools/workspace_and_nets.cc
  src/supervisedoutputconnector.h
  tests/CMakeLists.txt
  tests/ut-caffe2api.cc
Labels: API, C++, GPU, caffe2, images, model, neural net, python

#520 Making Caffe optional in builds
  CMakeLists.txt
  README.md
  main/dede.cc
  src/CMakeLists.txt
  src/backends/xgb/xgbmodel.cc
  src/deepdetect.cc
  src/imginputfileconn.h
  src/jsonapi.cc
  src/services.h
  tests/CMakeLists.txt
Labels: C++, Caffe, compilation
