Repository jolibrain/deepdetect, pull requests merged in 2019-11, with the labels that each got.

#658 Tf 131 update
  CMakeLists.txt
  docker/cpu-caffe-tf/Dockerfile
  docker/gpu-caffe-cpu-tf/Dockerfile
  docker/gpu-caffe-tf/Dockerfile
Labels: C++, tensorflow, v0.9.5

#664 Compiler warnings reduction
  src/mlmodel.h
  src/services.h
  src/simsearch.cc
  src/txtinputfileconn.cc
  src/txtinputfileconn.h
Labels: C++, compilation, v0.9.5

#661 Pytorch inference fixes
  src/backends/torch/torchinputconns.h
  src/backends/torch/torchlib.cc
  src/imginputfileconn.h
  tests/ut-torchapi.cc
Labels: API, pytorch, v0.9.5

#659 Add mutex to TensorRT prediction calls
  src/backends/tensorrt/tensorrtlib.cc
  src/backends/tensorrt/tensorrtlib.h
Labels: v0.9.5

#653 Updated dlib to 19.18
  CMakeLists.txt
  README.md
  src/backends/dlib/DNNStructures.h
  src/backends/dlib/dliblib.cc
Labels: v0.9.5

#660 Chains: avoid encoding + serializing crops, passing raw cv::Mat instead
  src/chain_actions.cc
  src/imginputfileconn.h
  src/services.h
Labels: chains, images, v0.9.5

#666 correct simsearch backend specification at compile time
  CMakeLists.txt
Labels: compilation, simsearch, v0.9.5
