Repository jolibrain/deepdetect, pull requests merged in 2019-08, with the labels that each got.

#605 Basic multi-models inference with intermediary operators via `/chain` API call
  clients/python/dd_client.py
  src/CMakeLists.txt
  src/apidata.cc
  src/apidata.h
  src/backends/caffe/caffeinputconns.h
  src/backends/caffe/caffelib.cc
  src/backends/caffe2/caffe2inputconns.h
  src/backends/caffe2/caffe2inputimg.cc
  src/backends/caffe2/caffe2inputinterface.cc
  src/backends/caffe2/caffe2lib.cc
  src/backends/dlib/dlibinputconns.h
  src/backends/tensorrt/tensorrtinputconns.cc
  src/backends/tensorrt/tensorrtinputconns.h
  src/backends/tensorrt/tensorrtlib.cc
  src/backends/xgb/xgbinputconns.cc
  src/backends/xgb/xgbinputconns.h
  src/chain.cc
  src/chain.h
  src/chain_actions.cc
  src/chain_actions.h
  src/httpjsonapi.cc
  src/imginputfileconn.h
  src/inputconnectorstrategy.h
  src/jsonapi.cc
  src/jsonapi.h
  src/mlservice.h
  src/services.h
  src/supervisedoutputconnector.h
  src/unsupervisedoutputconnector.h
  src/utils/utils.hpp
Labels: API, C++

#618 type fix for variants with long long int
  docker/cpu-ncnn-pi3/Dockerfile
  src/apidata.cc
  src/apidata.h
  src/chain.h
Labels: C++, compilation

#622 fixed spdlog missing header on raspberry 4
  src/mlservice.h
Labels: C++, compilation

#621 dede API for lookahead
  src/backends/caffe/caffelib.cc
Labels: API, optimizers

#623 dd api for caffe warmup
  src/backends/caffe/caffelib.cc
Labels: API, optimizers

#627 dede API for Decoupled wd : adamW and sgdW and amsgradW
  src/backends/caffe/caffelib.cc
Labels: API, Caffe, optimizers

#630 add API params for decoupled weight decay scheduler
  src/backends/caffe/caffelib.cc
Labels: API, Caffe, optimizers
