Repository jolibrain/deepdetect, pull requests merged in 2020-09, with the labels that each got.

#779 fix(build): ensure all xgboost submodules are checkouted
  CMakeLists.txt
Labels: bug, compilation

#782 feat(imginputfile): histogram equalization of input image
  examples/caffe/voc_roi/000010_bw.jpg
  examples/caffe/voc_roi/000010_bw_histogram_equalizer.yml
  examples/caffe/voc_roi/000010_histogram_equalizer.yml
  src/imginputfileconn.h
  tests/ut-conn.cc
Labels: ready to merge

#737 feat: native torch from prototxt using internal graph representation + timeseries with torch
  CMakeLists.txt
  README.md
  examples/graph/recurrent.prototxt
  src/CMakeLists.txt
  src/backends/caffe/caffeinputconns.cc
  src/backends/torch/torchgraphbackend.cc
  src/backends/torch/torchgraphbackend.h
  src/backends/torch/torchinputconns.cc
  src/backends/torch/torchinputconns.h
  src/backends/torch/torchlib.cc
  src/backends/torch/torchlib.h
  src/backends/torch/torchmodel.cc
  src/backends/torch/torchmodel.h
  src/basegraph.cc
  src/basegraph.h
  src/caffegraphinput.cc
  src/caffegraphinput.h
  src/csvinputfileconn.h
  src/csvtsinputfileconn.h
  src/generators/net_caffe.cc
  src/generators/net_caffe.h
  src/generators/net_caffe_recurrent.cc
  src/generators/net_caffe_recurrent.h
  src/graph.cc
  src/graph.h
  src/imginputfileconn.h
  src/jsonapi.cc
  src/services.h
  src/txtinputfileconn.h
  tests/CMakeLists.txt
  tests/ut-graph.cc
  tests/ut-torchapi.cc
Labels: ready to merge, v0.9.8

#806 fix: allows to specify size and color/bw with segmentation models
  src/backends/caffe/caffelib.cc
  src/backends/caffe/caffelib.h
Labels: Caffe, images, ready to merge

#807 fix: ssd_300_res_128 deploy file is missing a quote
  templates/caffe/ssd_300_res_128/deploy.prototxt
Labels: model, ready to merge

#801 fix: set caffe smooth l1 loss threshold to 1
  src/backends/caffe/caffelib.cc
Labels: Caffe, ready-to-review

#770 fix(TRT): refinedet
  CMakeLists.txt
  patches/trt/0001-support-for-refinedet.patch
Labels: bug, ready to merge, v0.9.8

#758 feat: add json output to dd_bench.py
  clients/python/dd_bench.py
Labels: ready-to-review

#767 support for torch 1.6
  CMakeLists.txt
  README.md
  patches/pytorch/pytorch_16_logging.patch
Labels: pytorch-upgrade, ready to merge, v0.9.8

#814 feat: added bw image input support to dd_bench
  clients/python/dd_bench.py
Labels: no-ci, python, ready-to-merge

#813 fix: build with -DUSE_TENSORRT_OSS=ON
  CMakeLists.txt
  ci/Jenkinsfile.unittests
Labels: compilation, ready-to-review, tensorrt

#805 feat(imginputfile): histogram equalization of input image
  clients/python/dd_bench.py
  examples/caffe/voc_roi/000010_bw.jpg
  examples/caffe/voc_roi/000010_bw_histogram_equalizer.yml
  examples/caffe/voc_roi/000010_histogram_equalizer.yml
  src/imginputfileconn.h
  tests/ut-conn.cc
Labels: API, images, ready-to-merge

#586 replace db:true by db:false in json files when copying models
  src/backends/caffe/caffemodel.cc
  src/utils/fileops.hpp
Labels: ready-to-merge

#824 build: moving to distribution/release of mapbox variant
  README.md
  src/apidata.h
  src/services.h
  src/utils/optional.hpp
  src/utils/recursive_wrapper.hpp
  src/utils/variant.hpp
  src/utils/variant_io.hpp
Labels: compilation, ready-to-review

#823 fix(dede): Remove unnecessary caffe include
  src/generators/net_caffe.h
Labels: compilation

#835 fix: convolution layer initialization of SE-ResNeXt network templates
  templates/caffe/se_resnext_101/se_resnext_101.prototxt
  templates/caffe/se_resnext_50/se_resnext_50.prototxt
Labels: datatype:images, kind:neural net, mllib:caffe, process:ready-to-review

#838 fix: add support and automated processing of categorical variables in timeseries data
  src/backends/caffe/caffeinputconns.cc
  src/backends/caffe/caffeinputconns.h
  src/csvinputfileconn.cc
  src/csvinputfileconn.h
  src/csvtsinputfileconn.cc
  src/csvtsinputfileconn.h
Labels: datatype:csv, datatype:timeseries, mllib:caffe, mllib:pytorch, process:ready-to-review

#831 chore: ignore caffe.pb.h warning
  src/CMakeLists.txt
Labels: process:ready-to-review

#841 fix: input image transforms in API doc
  docs/api.md
Labels: ci:skip, kind:documentation

#839 refactor: hide visitor complexity inside the visitor itself
  src/services.h
Labels: kind:C++, process:ready-to-review
