Repository jolibrain/deepdetect, pull requests merged in 2020-07, with the labels that each got.

#749 Force cudnn engine for refinedet
  src/backends/caffe/caffelib.cc
  src/backends/caffe/caffelib.h
Labels: Caffe, images, v0.9.8

#756 Fixing template generation for SSD with bw images
  src/backends/caffe/caffelib.cc
  src/backends/caffe/caffelib.h
Labels: images, v0.9.8

#757 [FIX] reversed precision and recall in case of classification + output all (per class) precision,recall,f1 if asked for
  src/backends/caffe/caffelib.cc
  src/supervisedoutputconnector.h
Labels: bug, v0.9.8

#755 Added key overflow warning at end of db serialization when an image key > 256 chars
  src/backends/caffe/caffeinputconns.cc
Labels: enhancement, ready to merge, v0.9.8

#759 Modifications for image multi target regression
  src/backends/caffe/caffeinputconns.cc
  src/backends/caffe/caffelib.cc
Labels: Caffe, enhancement, images, v0.9.8

#760 Allowing regression models into chains with nested outputs
  src/chain.cc
  src/services.h
Labels: chains, enhancement, model, v0.9.8

#741 Cleanup protoc selection
  CMakeLists.txt
  src/CMakeLists.txt
Labels: ready to merge, v0.9.8

#762 [Fix] Detect lmdb path with sparse models
  src/backends/caffe/caffeinputconns.h
Labels: bug, v0.9.8
