Repository jolibrain/deepdetect, pull requests merged in 2020-06, with the labels that each got.

#729 Additionnal ResNet-SSD intermediate architecture templates
  templates/caffe/resnet_18_ssd/deploy.prototxt
  templates/caffe/resnet_18_ssd/resnet_18_ssd.prototxt
  templates/caffe/resnet_18_ssd/resnet_18_ssd_solver.prototxt
  templates/caffe/resnet_34_ssd/deploy.prototxt
  templates/caffe/resnet_34_ssd/resnet_34_ssd.prototxt
  templates/caffe/resnet_34_ssd/resnet_34_ssd_solver.prototxt
Labels: Caffe, model, v0.9.8

#738 [FIX] image -> single target regression
  src/backends/caffe/caffelib.cc
Labels: images, v0.9.8

#743 [FIX] image based regression predict
  src/backends/caffe/caffelib.cc
Labels: bug, v0.9.8

#734 [FIX] dice loss for 2 classes + contour weighting
  src/backends/caffe/caffelib.cc
  tests/ut-caffe-mlp.cc
Labels: bug, v0.9.8

#715 torch lib on DBs
  CMakeLists.txt
  src/CMakeLists.txt
  src/backends/torch/db.cpp
  src/backends/torch/db.hpp
  src/backends/torch/db_lmdb.cpp
  src/backends/torch/db_lmdb.hpp
  src/backends/torch/llogging.h
  src/backends/torch/torchinputconns.cc
  src/backends/torch/torchinputconns.h
  src/backends/torch/torchlib.cc
  src/txtinputfileconn.h
Labels: pytorch, ready to merge, v0.9.8

#725 Torchlib production missing features
  src/backends/torch/torchlib.cc
  src/backends/torch/torchlib.h
  tests/ut-torchapi.cc
Labels: pytorch, ready to merge, v0.9.8

#735 [FIX] case where nologits available but raw measure asked for
  src/supervisedoutputconnector.h
Labels: ready to merge, v0.9.8

#747 TENSORRT_OSS : support for refinedet
  CMakeLists.txt
  patches/trt/0001-support-for-refinedet.patch
  patches/trt/detection_ARM.patch
  src/CMakeLists.txt
Labels: ready to merge, tensorrt, v0.9.8

#744 [FIX] segfault in case of predict with svmCaffeInputConn and db:true
  src/backends/caffe/caffeinputconns.cc
  src/backends/caffe/caffeinputconns.h
Labels: ready to merge, v0.9.8
