Repository jolibrain/deepdetect, pull requests merged in 2020-03, with the labels that each got.

#704 fix ut torchapi
  tests/CMakeLists.txt
  tests/ut-torchapi.cc
  tools/torch/trace_pytorch_transformers.py
Labels: v0.9.6.1

#702 geometry image deformation for detection/ssd
  src/backends/caffe/caffelib.cc
  src/backends/caffe/caffelib.h
Labels: v0.9.7

#699 fix wrt PR 693 (dlib chain / logger)
  src/backends/dlib/dlib_actions.cpp
  src/backends/dlib/dlib_actions.h
Labels: v0.9.7

#696 engine selection at service creation time : CAFFE of CUDNN
  src/backends/caffe/caffelib.cc
  src/backends/caffe/caffelib.h
Labels: v0.9.7

#709 fix: force caffe engine when (de)conv dilation > 1
  src/backends/caffe/caffelib.cc
  src/backends/caffe/caffelib.h
Labels: v0.9.7

#705 fix logging from output connectors + add error message in case of unsupervised output + no extract_layer
  src/backends/caffe/caffelib.cc
  src/backends/caffe2/caffe2lib.cc
  src/backends/dlib/dliblib.cc
  src/backends/ncnn/ncnnlib.cc
  src/backends/tensorrt/tensorrtlib.cc
  src/backends/tf/tflib.cc
  src/backends/torch/torchlib.cc
  src/backends/tsne/tsnelib.cc
  src/backends/xgb/xgblib.cc
  src/outputconnectorstrategy.h
  src/supervisedoutputconnector.h
  src/unsupervisedoutputconnector.h
Labels: v0.9.7

#713 Fix rotate action when upstream prediction is empty for some of the samples in a batch
  src/chain_actions.cc
Labels: bug, chains, v0.9.7

#711 added segmentation to benchmark script
  clients/python/dd_bench.py
Labels: python, v0.9.7

#697 add unit test for tensorrt backend
  tests/CMakeLists.txt
  tests/ut-tensorrtapi.cc
Labels: v0.9.7
