Repository jolibrain/deepdetect, pull requests merged in 2020-12, with the labels that each got.

#1041 ci: don't cache faiss build
  ci/Jenkinsfile.prebuilt-cache
Labels: ci:skip-tests, process:merge-queued, process:no-need-review

#1027 build(docker): always use our shared libs version
  .dockerignore
  docker/check-dede-deps.sh
  docker/cpu.Dockerfile
  docker/get_libs.sh
  docker/gpu.Dockerfile
  docker/gpu_tensorrt.Dockerfile
  docker/start-dede.sh
  get_models.sh
Labels: ci:docker, ci:skip-tests, process:no-need-review

#1020 feat: vision transformer (ViT) multi-gpu with torch
  src/backends/torch/native/templates/vit.cc
  src/backends/torch/native/templates/vit.h
  tests/ut-torchapi.cc
Labels: datatype:images, kind:neural net, mllib:pytorch, process:ready-to-review

#1040 ci: don't use /tmp as TMPDIR
  ci/Jenkinsfile.unittests
Labels: process:merge-queued, process:no-need-review

#1035 fix(torch): when resume, override solver parameters after solver reload
  src/backends/torch/torchsolver.cc
  src/backends/torch/torchsolver.h
Labels: mllib:pytorch, process:ready-to-review

#1042 fix(timeseries): throw exception if recurrent template w/o layers spe…
  src/generators/net_caffe_recurrent.cc
Labels: datatype:timeseries, process:ready-to-review

#1048 fix: init XXX_total_duration_ms to 0ms
  src/service_stats.h
  tests/ut-jsonapi.cc
Labels: process:merge-queued, process:no-need-review, process:ready-to-review

#1044 fix(csvts): clarify error msg on seq lengths
  src/backends/torch/torchinputconns.cc
Labels: datatype:timeseries, process:ready-to-review

#1043 fix(timeseries): throw if smthf wrong with scaling values
  src/csvinputfileconn.h
Labels: datatype:timeseries, process:ready-to-review

#1053 docs: add links to dd_platform_docker and helm_chart
  README.md
Labels: ci:skip-tests, process:ready-to-review

#1055 fix: missing libboost-stacktrace-dev dep in docs
  docs/source.md
Labels: ci:skip-tests, kind:documentation, process:merge-queued, process:no-need-review

#1052 fix(nbeats): stateless nbeats creation call for multi-gpu
  src/backends/torch/native/templates/nbeats.cc
Labels: process:ready-to-review

#1033 fix: torch image input connector mean and std scaling
  src/backends/torch/torchdataset.cc
Labels: datatype:images, mllib:pytorch, process:ready-to-review

#1047 fix(nbeats): fix loss for backcast part
  src/backends/torch/native/templates/nbeats.h
Labels: mllib:pytorch, process:merge-queued, process:ready-to-review

#1058 feat: use jolibrain fork of faiss
  CMakeLists.txt
Labels: ci:skip-tests, process:merge-queued, process:no-need-review

#1057 feat: add access log for oat++
  src/http/controller.hpp
  src/oatppjsonapi.cc
  src/oatppjsonapi.h
Labels: process:merge-queued, process:ready-to-review

#1054 chore: remove unused/not working tests
  ci/Jenkinsfile.unittests
  tests/CMakeLists.txt
  tests/test-server.cc
  tests/ut-httpapi.cc
Labels: process:merge-queued, process:ready-to-review

#1061 docs: add more explanations on scale documentation
  docs/api.md
Labels: ci:skip-tests, kind:documentation, process:merge-queued, process:ready-to-review

#1059 fix: ViT blocks modification for importing pre-trained models
  src/backends/torch/native/templates/vit.cc
  src/backends/torch/native/templates/vit.h
Labels: datatype:images, kind:neural net, mllib:pytorch, process:merge-queued, process:ready-to-review

#1067 fix: ddimg logger ptr
  src/imginputfileconn.h
Labels: datatype:images, process:merge-queued, process:ready-to-review

#1066 feat: service stats provide predict and transform duration total
  src/service_stats.cc
  tests/ut-jsonapi.cc
Labels: kind:API, process:merge-queued, process:ready-to-review

#1056 chore: ensure we don't build cpu only version if CUDA is missing
  CMakeLists.txt
Labels: ci:docker, process:merge-queued, process:ready-to-review

#1051 build(tensorrt): enabled only tensorrt in tensorrt docker image
  build.sh
Labels: ci:docker, process:merge-queued, process:ready-to-review

#953 feat(torch): Add native resnet support
  CMakeLists.txt
  docker/cpu.Dockerfile
  docker/get_libs.sh
  docker/gpu.Dockerfile
  docker/gpu_tensorrt.Dockerfile
  src/CMakeLists.txt
  src/backends/torch/native/native_factory.cc
  src/backends/torch/native/native_factory.h
  src/backends/torch/native/native_net.h
  src/backends/torch/native/native_wrapper.h
  src/backends/torch/native/templates/vision_models.h
  src/backends/torch/native/templates/vit.h
  tests/ut-torchapi.cc
Labels: datatype:images, kind:neural net, mllib:pytorch, process:merge-queued, process:ready-to-review

#1069 feat(tools): trace_torchvision can trace models for loading weights w…
  tools/torch/trace_torchvision.py
Labels: ci:skip-tests, mllib:pytorch, process:merge-queued, process:ready-to-review

#1063 refactor(torch): change parameter initialization order for clarity
  src/backends/torch/torchlib.cc
Labels: mllib:pytorch, process:merge-queued, process:ready-to-review, type:enhancement

#1071 chore(readme): fix typo
  README.md
Labels: ci:skip-tests, process:merge-queued, process:ready-to-review

#1072 fix(torch): also remove not best models in case of native model
  src/backends/torch/torchlib.cc
Labels: mllib:pytorch, process:merge-queued, process:ready-to-review

#1075 fix: ensure redownloaded test archives are extracted
  tests/CMakeLists.txt
Labels: ci:skip-tests, process:merge-queued, process:no-need-review

#1074 fix: simsearch build with annoy
  CMakeLists.txt
  src/simsearch.cc
  src/simsearch.h
Labels: mllib:simsearch, process:merge-queued, process:ready-to-review

#1073 chore(torch): replace "virtual" by "override" in torch native models
  src/backends/torch/native/templates/nbeats.h
  src/backends/torch/native/templates/vit.h
Labels: mllib:pytorch, process:merge-queued, process:ready-to-review

#1079 ci: fix download not zipped files
  tests/CMakeLists.txt
Labels: ci:skip-tests, process:no-need-review

#1076 feat(torch): add wide resnet and resnext to the vision models
  src/backends/torch/native/templates/vision_models.h
Labels: kind:model, mllib:pytorch, process:merge-queued, process:ready-to-review

#1064 fix(torch/timeseries): restore previous behavior wrt timesteps API pa…
  docs/api.md
  src/backends/torch/torchinputconns.cc
  src/backends/torch/torchinputconns.h
  tests/ut-graph.cc
  tests/ut-torchapi.cc
Labels: datatype:timeseries, mllib:pytorch, process:merge-queued, process:ready-to-review

#1065 fix: tentative torch faster tests
  tests/CMakeLists.txt
  tests/ut-torchapi.cc
Labels: mllib:pytorch, process:merge-queued, process:ready-to-review

#1083 refactor: make logger torch-friendly
  CMakeLists.txt
  patches/pytorch/pytorch_16_new_logger.patch
  patches/pytorch/pytorch_16_use_new_logger.patch
  src/backends/torch/llogging.h
  src/backends/torch/torchutils.h
  src/backends/xgb/xgb_dmlc_macro_fix.h
Labels: ci:full-build, kind:C++, mllib:pytorch, process:merge-queued, process:ready-to-review

#1097 docs: add how to build like the ci does
  README.md
  docs/ci.md
Labels: ci:skip-tests, process:merge-queued, process:ready-to-review

#1094 fix: some HTTP return codes
  src/jsonapi.cc
  src/jsonapi.h
Labels: process:ready-to-review

#1084 fix: forward our cuda to xgboost
  CMakeLists.txt
Labels: process:merge-queued, process:no-need-review, process:ready-to-review

#1036 chore: activate ci for multigpu tests
  ci/Jenkinsfile.unittests
Labels: process:merge-queued, process:no-need-review

#1089 fix: allows mean+std image transform with NCNN inference
  src/backends/ncnn/ncnninputconns.h
  tests/ut-ncnnapi.cc
Labels: datatype:images, mllib:NCNN, process:ready-to-review

#1086 Torch 171
  CMakeLists.txt
  docker/cpu.Dockerfile
  docker/gpu.Dockerfile
  tests/ut-torchapi.cc
Labels: ci:docker, ci:full-build, mllib:pytorch, process:merge-queued, process:ready-to-review

#1091 fix: ONNX tensorrt engine with correct enqueueV2
  src/backends/tensorrt/tensorrtlib.cc
  src/backends/tensorrt/tensorrtlib.h
Labels: datatype:images, mllib:tensorrt, process:merge-queued, process:ready-to-review

#1088 fix: reraise same signal on abort
  src/httpjsonapi.cc
  src/oatppjsonapi.cc
Labels: process:merge-queued, process:ready-to-review

#1099 fix: scale image input with NCNN
  src/backends/ncnn/ncnninputconns.h
  tests/ut-ncnnapi.cc
Labels: datatype:images, mllib:NCNN, process:ready-to-review

#1100 fix: models flops and number of parameters in API
  src/mllibstrategy.h
Labels: kind:API, kind:model, process:merge-queued, process:ready-to-review

#1098 fix: NCNN backend using the common protobuf
  CMakeLists.txt
Labels: build:compilation, ci:full-build, mllib:NCNN, process:ready-to-review

#1101 fix: tensorrt max workspace size overflow
  src/backends/tensorrt/tensorrtlib.cc
  src/backends/tensorrt/tensorrtlib.h
Labels: mllib:tensorrt, process:merge-queued, process:ready-to-review

#1070 feat(torch): native models can load weights from any jit file
  src/backends/torch/torchmodule.cc
  src/backends/torch/torchutils.cc
  src/backends/torch/torchutils.h
Labels: mllib:pytorch, process:merge-queued, process:ready-to-review

#1102 fix: tensorrt input size for caffe source models
  src/backends/tensorrt/protoUtils.cc
  src/backends/tensorrt/protoUtils.h
  src/backends/tensorrt/tensorrtlib.cc
  src/backends/tensorrt/tensorrtlib.h
  src/backends/tensorrt/tensorrtmodel.cc
  src/backends/tensorrt/tensorrtmodel.h
  tests/ut-tensorrtapi.cc
Labels: datatype:images, mllib:tensorrt, process:merge-queued, process:ready-to-review
