Repository jolibrain/deepdetect, pull requests merged in 2020-10, with the labels that each got.

#829 feat(stats): added service statistics mechanism
  src/CMakeLists.txt
  src/backends/caffe/caffelib.cc
  src/backends/dlib/dliblib.cc
  src/backends/ncnn/ncnnlib.cc
  src/backends/tensorrt/tensorrtinputconns.cc
  src/backends/tensorrt/tensorrtinputconns.h
  src/backends/tensorrt/tensorrtlib.cc
  src/backends/tf/tflib.cc
  src/backends/torch/torchlib.cc
  src/backends/xgb/xgblib.cc
  src/jsonapi.cc
  src/mllibstrategy.h
  src/mlservice.h
  src/service_stats.cc
  src/service_stats.h
  tests/ut-jsonapi.cc
  tests/ut-torchapi.cc
Labels: kind:API, process:ready-to-review, type:enhancement

#844 Fix(nbeats): implement paper trend and seasonality
  src/backends/torch/native/templates/nbeats.cc
Labels: datatype:timeseries, mllib:pytorch, process:ready-to-review

#845 fix: update caffe cudnn engine without template
  src/backends/caffe/caffelib.cc
Labels: mllib:caffe, process:ready-to-review

#834 feat(dede): Training for image classification with torch
  src/backends/torch/torchinputconns.cc
  src/backends/torch/torchinputconns.h
  src/backends/torch/torchlib.cc
  src/backends/torch/torchlib.h
  src/imginputfileconn.h
  tests/CMakeLists.txt
  tests/ut-torchapi.cc
Labels: datatype:images, mllib:pytorch, process:ready-to-review

#846 chore: bump TensorRT version to 20.09
  CMakeLists.txt
Labels: mllib:tensorrt

#842 fix(native) fix no template param, fallback to default
  src/backends/torch/native/native_factory.h
  src/backends/torch/native/templates/nbeats.h
Labels: datatype:timeseries, mllib:pytorch, process:ready-to-review

#827 Graph lstm autoencoder
  src/backends/caffe/caffelib.cc
  src/backends/torch/torchgraphbackend.cc
  src/backends/torch/torchlib.cc
  src/basegraph.cc
  src/caffegraphinput.cc
  src/generators/net_caffe_recurrent.cc
  src/generators/net_caffe_recurrent.h
  tests/ut-graph.cc
Labels: datatype:timeseries, kind:model, mllib:pytorch, process:ready-to-review

#849 fix(tests): inc iteration of torchapi.service_train_image test
  tests/ut-torchapi.cc
Labels: mllib:pytorch

#852 fix: in tensorrt builds, remove forced cuda version and unused lib output + force-select tensorrt when tensorrt_oss is selected
  CMakeLists.txt
Labels: build:compilation, mllib:tensorrt, process:ready-to-review

#854 feat(build): add script to create cppnet-lib debian package
  .gitignore
  tools/build-cpp-netlib-pkg.sh
Labels: build:compilation, ci:skip

#833 Torch extract layer + NBEATS layer extract
  src/backends/torch/native/native_net.h
  src/backends/torch/native/templates/nbeats.cc
  src/backends/torch/native/templates/nbeats.h
  src/backends/torch/torchgraphbackend.cc
  src/backends/torch/torchgraphbackend.h
  src/backends/torch/torchlib.cc
  src/backends/torch/torchlib.h
  tests/ut-graph.cc
  tests/ut-torchapi.cc
Labels: datatype:timeseries, mllib:pytorch, process:ready-to-review

#851 csvts / torch : warn if there is not enough timesteps in a sequence
  src/backends/torch/torchinputconns.cc
Labels: mllib:pytorch, process:ready-to-review

#850 feat(build): allow to change CUDA_ARCH
  build.sh
Labels: build:compilation, mllib:caffe

#860 fix: missing variant package in docker files
  docker/cpu.Dockerfile
  docker/gpu.Dockerfile
Labels: build:compilation, ci:skip, kind:docker

#848 Feat nbeats expose hidden size in api
  docs/api.md
  src/backends/torch/native/templates/nbeats.h
Labels: datatype:timeseries, mllib:pytorch, process:ready-to-review

#861 fix: remove unecessary limit setting call to protobuf codedstream
  src/backends/ncnn/caffe2ncnn.cc
Labels: build:compilation, mllib:NCNN

#853 refactor: register internal matrices in nbeats, makes code a lot simpler
  src/backends/torch/native/native_net.h
  src/backends/torch/native/templates/nbeats.cc
  src/backends/torch/native/templates/nbeats.h
Labels: datatype:timeseries, mllib:pytorch, process:ready-to-review

#863 fix(csvts): correctly store and print test file names
  src/backends/torch/torchinputconns.cc
  src/csvtsinputfileconn.cc
  src/csvtsinputfileconn.h
Labels: datatype:timeseries, process:ready-to-review

#864 fix(torch/timeseries): unscale prediction output if needed
  src/backends/torch/torchlib.cc
  src/backends/torch/torchlib.h
Labels: datatype:timeseries, mllib:pytorch, process:ready-to-review

#859 feat(timeseries): MAPE, sMAPE, MASE, OWA metrics
  docs/api.md
  src/supervisedoutputconnector.h
  tests/ut-graph.cc
Labels: datatype:timeseries, process:ready-to-review

#867 fix(torch): Fix conditions to add classification head.
  src/backends/torch/torchlib.cc
  src/imginputfileconn.h
  tests/ut-torchapi.cc
Labels: mllib:pytorch

#868 fix: fix split_data in csvts connector
  src/csvinputfileconn.cc
  src/csvinputfileconn.h
  src/csvtsinputfileconn.cc
  src/csvtsinputfileconn.h
Labels: datatype:csv, datatype:timeseries, kind:documentation, process:ready-to-review

#873 fix(torch/timeseries): do not double read query data
  src/backends/torch/torchinputconns.cc
Labels: datatype:timeseries, mllib:pytorch, process:ready-to-review

#875 docs: Fix documentation for scale in ImageInputConntector
  docs/api.md
Labels: datatype:images, kind:API, kind:documentation, process:ready-to-review

#877 fix: proper cleanup of tensorrt models and services
  src/backends/tensorrt/tensorrtlib.cc
  tests/ut-tensorrtapi.cc
Labels: mllib:tensorrt, process:ready-to-review

#872 fix(csvts/torch): allow to read csv timeserie directly from query
  src/backends/torch/torchinputconns.cc
Labels: datatype:timeseries, mllib:pytorch, process:ready-to-review

#878 build(docker): add missing python3-yaml
  docker/cpu.Dockerfile
  docker/gpu.Dockerfile
  docker/gpu_tensorrt.Dockerfile
  docker/sync_gpu_dockerfiles.sh
Labels: ci:docker, kind:docker

#881 docs: remove IRC link
  README.md
Labels: process:ready-to-review

#880 docs: rework header tables
  README.md
Labels: process:ready-to-review

#879 docs: remove reference of Ubuntu 16.04
  ISSUE_TEMPLATE.md
  README.md
Labels: process:ready-to-review

#865 fix(torch): load weights only once
  src/backends/torch/torchgraphbackend.cc
  src/backends/torch/torchgraphbackend.h
  src/backends/torch/torchlib.cc
  src/backends/torch/torchlib.h
  src/caffegraphinput.cc
  src/caffegraphinput.h
Labels: mllib:pytorch, process:ready-to-review

#890 fix: handle int64 in conversion from json to APIData
  src/apidata.cc
Labels: process:ready-to-review, type:bug

#888 fix: docker adds missing pytorch deps
  build.sh
  docker/cpu.Dockerfile
  docker/get_libs.sh
  docker/gpu.Dockerfile
  docker/gpu_tensorrt.Dockerfile
Labels: build:compilation, ci:docker, kind:docker

#894 chore: update tensorrt API to remove deprecated calls
  src/backends/tensorrt/tensorrtlib.cc
  src/backends/tensorrt/tensorrtlib.h
Labels: mllib:tensorrt

#896 fix: readme table of backends, models and data formats
  README.md
Labels: ci:skip, kind:documentation, process:ready-to-review

#906 build: rework examples download
  ci/Jenkinsfile.unittests
  tests/CMakeLists.txt
Labels: build:compilation, ci:no-datasets-cache

#903 refactor(image): Remove duplicate code in ImgInputConnector
  src/backends/torch/torchinputconns.cc
  src/imginputfileconn.h
Labels: datatype:images, kind:connectors, process:ready-to-review

#884 feat(tensorrt): Add support for onnx image classification models
  src/backends/tensorrt/tensorrtinputconns.cc
  src/backends/tensorrt/tensorrtlib.cc
  src/backends/tensorrt/tensorrtlib.h
  src/backends/tensorrt/tensorrtmodel.cc
  src/backends/tensorrt/tensorrtmodel.h
  tests/CMakeLists.txt
  tests/ut-tensorrtapi.cc
Labels: mllib:tensorrt, process:ready-to-review

#905 feat(ml): tensorrt support for regression models
  docs/api.md
  src/backends/tensorrt/tensorrtlib.cc
  src/backends/tensorrt/tensorrtlib.h
Labels: datatype:images, mllib:tensorrt, process:ready-to-review

#886 fix(torch/native): prevent loading weights before instanciating native
  src/backends/torch/torchlib.cc
Labels: mllib:pytorch, process:ready-to-review

#883 ci: enable faiss
  ci/Jenkinsfile.unittests
Labels: build:compilation, process:ready-to-review

#902 feat(api): add versions and compile flags to /info
  CMakeLists.txt
  build.sh
  dd_config.h.in
  docker/cpu.Dockerfile
  src/dd_config.h.in
  src/deepdetect.cc
  src/githash.h.in
  src/jsonapi.cc
  tools/build-docker-images.sh
Labels: build:compilation, process:ready-to-review

#908 fix(doc): update to neural network templates and output connector
  docs/api.md
Labels: ci:skip, kind:documentation, process:ready-to-review

#913 fix: tensorrt fp16 and int8 selector
  src/backends/tensorrt/tensorrtlib.cc
Labels: mllib:tensorrt, process:ready-to-review

#912 fix(stats): measure of inference count
  src/backends/torch/torchlib.cc
Labels: process:ready-to-review

#904 torch ranger
  docs/api.md
  src/CMakeLists.txt
  src/backends/torch/native/native_factory.cc
  src/backends/torch/native/native_factory.h
  src/backends/torch/native/native_net.h
  src/backends/torch/optim/ranger.cc
  src/backends/torch/optim/ranger.h
  src/backends/torch/torchUtils.h
  src/backends/torch/torchlib.cc
  src/backends/torch/torchlib.h
  src/backends/torch/torchmodule.cc
  src/backends/torch/torchmodule.h
  src/backends/torch/torchsolver.cc
  src/backends/torch/torchsolver.h
  src/backends/torch/torchutils.cc
  tests/ut-torchapi.cc
Labels: kind:optimizers, mllib:pytorch, process:ready-to-review

#911 fix: building documentation up to date for 18.04, tensorrt and tests
  docs/source.md
Labels: ci:skip, kind:documentation, process:ready-to-review

#901 feat(caffe): add new optimizers flavors to API
  docs/api.md
  src/backends/caffe/caffelib.cc
Labels: kind:optimizers, mllib:caffe, process:ready-to-review

#907 feat: make python client an install package
  .gitignore
  clients/python/README.md
  clients/python/dd_bench.py
  clients/python/dd_client/__init__.py
  clients/python/dd_client/bench.py
  clients/python/setup.cfg
  clients/python/setup.py
Labels: client:python, process:ready-to-review

#914 chore(python): introduce some minimal code rules
  ci/Jenkinsfile.unittests
  clients/python/.gitignore
  clients/python/README.md
  clients/python/dd_client/__init__.py
  clients/python/dd_client/bench.py
  clients/python/setup.cfg
  clients/python/setup.py
  clients/python/tox.ini
Labels: client:python, process:ready-to-review

#918 build: upgrade cppnet-lib to 0.13
  CMakeLists.txt
  docker/cpu.Dockerfile
  docker/gpu.Dockerfile
  docker/gpu_tensorrt.Dockerfile
  docs/source.md
Labels: build:compilation, process:ready-to-review

#910 build: change min cmake version
  CMakeLists.txt
Labels: build:compilation, process:ready-to-review

#922 ci(release): fix docker pull command escape
  ci/Jenkinsfile.docker
  ci/build-docker-images.sh
  ci/release.sh
Labels: ci:skip

#923 docs: Remove trailing whitespaces in doc
  docs/api.md
Labels: ci:skip, kind:documentation, process:ready-to-review
