Repository jolibrain/deepdetect, pull requests merged in 2020-11, with the labels that each got.

#926 fix(graph): correctly discard dropout
  src/generators/net_caffe_recurrent.cc
Labels: mllib:pytorch, process:ready-to-review

#927 build: caffe2 deprecation warning
  CMakeLists.txt
Labels: build:compilation, process:ready-to-review

#930 ci: downgrade cppnet to 0.11.2
  CMakeLists.txt
  docs/source.md
Labels: ci:docker, process:ready-to-review

#929 fix(timeseries): do not segfault if no valid files in train/test dir
  src/csvtsinputfileconn.cc
  tests/ut-conn.cc
Labels: datatype:timeseries, process:ready-to-review

#935 fix: missing main in bench.py
  clients/python/dd_client/bench.py
Labels: ci:skip, client:python

#933 fix: ignore JSON conversion throw in partial chains output
  src/apidata.h
Labels: kind:API, kind:chains, process:ready-to-review

#928 feat: one protobuf to rule them all
  CMakeLists.txt
  docker/get_libs.sh
  main/CMakeLists.txt
  src/CMakeLists.txt
  tests/CMakeLists.txt
Labels: build:compilation, ci:pytorch-upgrade, process:ready-to-review

#937 build: add missing cppnet-lib cmake dependency
  src/CMakeLists.txt
Labels: build:compilation, process:ready-to-review

#943 fix(torch): reload solver params on device from current learning, not previous one
  src/backends/torch/torchlib.cc
  src/backends/torch/torchmodule.cc
  src/backends/torch/torchsolver.cc
  src/backends/torch/torchsolver.h
Labels: mllib:pytorch, process:ready-to-review

#947 feat(bench): support for regression model benchmarking
  clients/python/dd_client/bench.py
Labels: client:python

#946 chore(torch): give more tolerance to unit test
  tests/ut-torchapi.cc
Labels: mllib:pytorch, process:ready-to-review

#951 fix: tensorrt output layer lookup now throws when layer does not exist
  src/backends/tensorrt/tensorrtlib.cc
Labels: mllib:tensorrt, process:ready-to-review

#942 fix: add tool to generate debian buster image with the workaround
  tools/build_docker_images_with_debian_workaround.sh
Labels: process:ready-to-review

#932 chore(torch): add doc + minor cleanups
  src/backends/torch/torchinputconns.cc
  src/backends/torch/torchinputconns.h
  src/backends/torch/torchlib.cc
  src/backends/torch/torchlib.h
  src/backends/torch/torchmodel.h
  src/backends/torch/torchmodule.cc
  src/backends/torch/torchmodule.h
  src/backends/torch/torchsolver.cc
  src/backends/torch/torchsolver.h
  src/backends/torch/torchutils.cc
  src/backends/torch/torchutils.h
Labels: mllib:pytorch, process:ready-to-review

#925 fix(torch): Raise an exception if gpu is not available
  src/backends/torch/torchlib.cc
Labels: kind:API, mllib:pytorch, process:ready-to-review

#950 fix(torch): clip gradient in rectified adam as stated in annex B of o…
  docs/api.md
  src/backends/torch/optim/ranger.cc
  src/backends/torch/optim/ranger.h
  src/backends/torch/torchsolver.cc
  src/backends/torch/torchsolver.h
Labels: mllib:pytorch, process:ready-to-review

#956 fix(torch): best model was never saved on last iteration
  src/backends/torch/torchlib.cc
Labels: mllib:pytorch, process:ready-to-review

#958 chore: follow-up 6d1aa4d
  src/backends/torch/torchlib.cc
Labels: process:ready-to-review

#962 fix(build): allow cmake 3.10 (Ubuntu 18.04) for builds with -DUSE_CPU_ONLY=ON
  CMakeLists.txt
Labels: build:compilation, process:ready-to-review

#944 fix(torch): correctly implements range state comparison
  src/backends/torch/optim/ranger.cc
  src/backends/torch/optim/ranger.h
Labels: mllib:pytorch, process:ready-to-review

#924 feat(ml): image regression model training with libtorch
  README.md
  docs/api.md
  src/backends/torch/torchinputconns.cc
  src/backends/torch/torchinputconns.h
  src/backends/torch/torchlib.cc
  src/backends/torch/torchlib.h
  src/backends/torch/torchmodule.cc
  src/backends/torch/torchmodule.h
  tests/ut-torchapi.cc
Labels: datatype:images, mllib:pytorch, process:ready-to-review

#941 feat: one protobuf to rule them all
  CMakeLists.txt
  ci/Jenkinsfile.prebuilt-cache
  ci/Jenkinsfile.unittests
  docker/get_libs.sh
  main/CMakeLists.txt
  src/CMakeLists.txt
  tests/CMakeLists.txt
Labels: ci:docker, ci:full-build

#968 feat(torch): clip gradient options for all optimizers
  docs/api.md
  src/backends/torch/optim/ranger.cc
  src/backends/torch/optim/ranger.h
  src/backends/torch/torchsolver.cc
  src/backends/torch/torchsolver.h
  tests/ut-torchapi.cc
Labels: mllib:pytorch, process:ready-to-review

#964 feat: allow to disable warning on build
  CMakeLists.txt
Labels: build:compilation, process:ready-to-review

#981 ci: sync github and dockerhub readme
  ci/Jenkinsfile.docker
Labels: process:ready-to-review

#983 fix: broken API doc formatting
  docs/api.md
Labels: ci:skip, kind:documentation, process:ready-to-review

#991 docs: fix markdown errors and missing stuff
  docs/api.md
Labels: ci:skip, kind:documentation, process:ready-to-review

#963 build: allow to build spdlog instead of using system lib
  CMakeLists.txt
  src/CMakeLists.txt
Labels: build:compilation, process:ready-to-review

#987 fix(torch/timeseries): check if number of labels is not larger than n…
  src/backends/torch/torchinputconns.cc
Labels: mllib:pytorch, process:ready-to-review

#992 chore: make sure model files don't remain in torch training unit tests
  tests/ut-torchapi.cc
Labels: mllib:pytorch, process:ready-to-review

#970 refactor(torch): make TorchDataset::get_batch code clearer
  src/backends/torch/torchdataset.cc
Labels: kind:connectors, mllib:pytorch, process:ready-to-review

#952 feat(ml): added vision tranformer (ViT) as torch native template
  src/CMakeLists.txt
  src/backends/torch/native/native_factory.cc
  src/backends/torch/native/native_factory.h
  src/backends/torch/native/templates/vit.cc
  src/backends/torch/native/templates/vit.h
  src/backends/torch/torchlib.cc
  src/backends/torch/torchmodule.cc
  src/backends/torch/torchmodule.h
  tests/ut-torchapi.cc
Labels: datatype:images, kind:neural net, mllib:pytorch, process:ready-to-review

#988 feat(torch): implement resume mllib option for torchlib: if true, reu…
  docs/api.md
  src/backends/torch/torchlib.cc
  src/backends/torch/torchsolver.cc
  src/backends/torch/torchsolver.h
  tests/ut-torchapi.cc
Labels: mllib:pytorch, process:ready-to-review

#957 feat(graph): correct data size computation if different ouputs of an …
  src/CMakeLists.txt
  src/backends/torch/torchgraphbackend.cc
  src/backends/torch/torchgraphbackend.h
  src/backends/torch/torchmodule.cc
  src/generators/net_caffe_recurrent.cc
  src/graph/basegraph.cc
  src/graph/basegraph.h
  src/graph/baseoperators.cc
  src/graph/baseoperators.h
  src/graph/caffegraphinput.cc
  src/graph/caffegraphinput.h
  src/graph/graph.cc
  src/graph/graph.h
  tests/ut-graph.cc
Labels: kind:graph, process:ready-to-review

#979 fix(torch/native) : do not fail if trying to load weights before (lat…
  src/backends/torch/torchmodule.cc
Labels: mllib:pytorch, process:ready-to-review

#994 docs: add some badges in README.md
  README.md
Labels: ci:skip, process:ready-to-review

#961 docker: don't install headers on gpu runtime image
  docker/cpu.Dockerfile
  docker/gpu.Dockerfile
  docker/gpu_tensorrt.Dockerfile
  docker/sync_gpu_dockerfiles.sh
Labels: process:no-need-review, process:ready-to-review

#976 fix: tensorrt refinedet CI and linking to nvcaffeparsers with tensorrt OSS
  CMakeLists.txt
  tests/CMakeLists.txt
  tests/ut-tensorrtapi.cc
Labels: mllib:tensorrt, process:no-need-review, process:ready-to-review

#955 fix(torch): Display correct remaining time and iter time
  src/backends/torch/torchlib.cc
Labels: kind:API, mllib:pytorch, process:ready-to-review

#993 feat: print stacktrace on segfault
  CMakeLists.txt
  src/httpjsonapi.cc
  src/httpjsonapi.h
Labels: process:ready-to-review

#998 chore: refactor of torchdataset db operations
  src/backends/torch/torchdataset.cc
  src/backends/torch/torchdataset.h
  src/backends/torch/torchinputconns.cc
  src/backends/torch/torchinputconns.h
Labels: mllib:pytorch, process:ready-to-review

#995 feat(torch/timeseries): add (p)ReLU layers in recurrent template,
  docs/api.md
  src/backends/torch/torchgraphbackend.cc
  src/generators/net_caffe_recurrent.cc
  src/generators/net_caffe_recurrent.h
  src/graph/baseoperators.cc
  src/graph/baseoperators.h
  src/graph/caffegraphinput.cc
  tests/ut-graph.cc
Labels: datatype:timeseries, mllib:pytorch, process:ready-to-review

#1000 feat: gives also per target error and not only global eucl when selec…
  src/supervisedoutputconnector.h
Labels: process:ready-to-review

#1001 fix: fix compilation w/o caffe
  CMakeLists.txt
  src/CMakeLists.txt
Labels: process:no-need-review, process:ready-to-review

#975 feat: introduce aotpp interface for deepdetect
  CMakeLists.txt
  ci/Jenkinsfile.prebuilt-cache
  ci/Jenkinsfile.unittests
  main/CMakeLists.txt
  main/dede.cc
  src/CMakeLists.txt
  src/deepdetect.cc
  src/http/app_component.hpp
  src/http/controller.hpp
  src/http/error_handler.cpp
  src/http/error_handler.hpp
  src/http/flags.h
  src/http/swagger_component.hpp
  src/httpjsonapi.cc
  src/oatppjsonapi.cc
  src/oatppjsonapi.h
  src/utils/utils.hpp
  tests/CMakeLists.txt
  tests/ut-oatpp.cc
  tests/ut-oatpp.h
Labels: process:no-need-review, process:ready-to-review

#1005 fix: setuptools drop support of python27
  clients/python/setup.py
Labels: ci:skip, process:no-need-review, process:ready-to-review

#1004 ci(docker): add missing libboost-stacktrace
  docker/cpu.Dockerfile
  docker/gpu.Dockerfile
  docker/gpu_tensorrt.Dockerfile
Labels: ci:docker, ci:skip, process:no-need-review, process:ready-to-review

#1009 build: don't always rebuild caffe.pb.h
  CMakeLists.txt
Labels: ci:skip, process:no-need-review

#999 build: don't git clone manually
  CMakeLists.txt
  docker/get_libs.sh
  patches/xgboost/static-lib.patch
Labels: build:compilation, process:ready-to-review

#1006 Improvements to torch db
  src/backends/torch/torchdataset.cc
  src/backends/torch/torchdataset.h
  src/backends/torch/torchinputconns.cc
  src/backends/torch/torchinputconns.h
Labels: mllib:pytorch, process:ready-to-review

#1007 build: BUILD_TESTS must required gtest
  tests/CMakeLists.txt
Labels: process:no-need-review, process:ready-to-review

#1011 fix(csv): remove trailing \n from header if there are any
  src/csvinputfileconn.cc
Labels: datatype:csv, datatype:timeseries, process:ready-to-review

#1008 feat(torch/timeseries): log much more info on data
  src/backends/torch/torchgraphbackend.cc
  src/backends/torch/torchgraphbackend.h
  src/backends/torch/torchinputconns.cc
  src/backends/torch/torchmodule.cc
Labels: datatype:timeseries, mllib:pytorch, process:ready-to-review

#1010 build: simplify lib dependencies
  CMakeLists.txt
  src/CMakeLists.txt
Labels: build:compilation, process:no-need-review, process:ready-to-review

#1018 fix(csvts): fix typo in logged msg
  src/backends/torch/torchinputconns.cc
Labels: datatype:timeseries, mllib:pytorch, process:no-need-review

#1016 fix: do not display all euclidean metrics for autoencoders
  src/backends/caffe/caffelib.cc
  src/supervisedoutputconnector.h
Labels: mllib:caffe, process:ready-to-review

#1012 chore: remove useless xgboost cmake flag
  CMakeLists.txt
Labels: process:no-need-review, process:ready-to-review

#1015 feat(ml): torch db stores encoded images instead of tensors
  src/backends/torch/torchdataset.cc
  src/backends/torch/torchdataset.h
  src/backends/torch/torchinputconns.cc
  src/backends/torch/torchinputconns.h
Labels: kind:connectors, mllib:pytorch, process:ready-to-review

#1017 fix(torch): loosen ut test
  tests/ut-torchapi.cc
Labels: datatype:timeseries, mllib:pytorch, process:ready-to-review

#1002 feat: add some more error messages to log
  src/mlmodel.h
Labels: process:merge-queued, process:ready-to-review

#980 feat(torch/nbeats): allow different sizes for backcast and forecast ,…
  docs/api.md
  src/backends/torch/native/native_net.h
  src/backends/torch/native/templates/nbeats.cc
  src/backends/torch/native/templates/nbeats.h
  src/backends/torch/torchinputconns.cc
  src/backends/torch/torchinputconns.h
  src/backends/torch/torchlib.cc
  src/csvtsinputfileconn.cc
  tests/ut-graph.cc
  tests/ut-torchapi.cc
Labels: mllib:pytorch, process:merge-queued, process:ready-to-review

#1023 build(tensorrt): merge flags TENSORRT and TENSORRT_OSS
  CMakeLists.txt
  build.sh
  src/CMakeLists.txt
Labels: build:compilation, ci:skip, process:merge-queued, process:no-need-review, process:ready-to-review

#1025 build(tensorrt): don't build samples
  CMakeLists.txt
Labels: ci:skip, process:merge-queued, process:no-need-review

#1029 ci: fix docker image tag typo
  ci/release.sh
Labels: ci:skip, process:merge-queued, process:no-need-review

#1019 refactor(graph): much saner namespaces / class names
  src/CMakeLists.txt
  src/backends/torch/torchgraphbackend.cc
  src/backends/torch/torchgraphbackend.h
  src/graph/basegraph.cc
  src/graph/basegraph.h
  src/graph/caffeinput.cc
  src/graph/caffeinput.h
  src/graph/graph.cc
  src/graph/graph.h
  src/graph/operators.cc
  src/graph/operators.h
Labels: kind:graph, process:ready-to-review

#1030 fix(ViT): typo that changed computations a lot
  src/backends/torch/native/templates/vit.cc
Labels: mllib:pytorch, process:ready-to-review

#1022 feat: provide predict/transform duration in ms
  src/service_stats.cc
  src/service_stats.h
Labels: process:ready-to-review

#1031 build: use caffe.pb.h is generated first
  CMakeLists.txt
Labels: ci:skip, process:merge-queued, process:no-need-review

#1037 fix(torch): loosen ut test 2
  tests/ut-torchapi.cc
Labels: ci:skip, process:no-need-review

#1028 build: let cmake handle tensorrt update
  CMakeLists.txt
Labels: build:compilation, ci:skip-tests, process:merge-queued, process:no-need-review
