Repository jolibrain/deepdetect, pull requests merged in 2020-02, with the labels that each got.

#693 Support for logger from within chain actions
  src/chain_actions.cc
  src/chain_actions.h
  src/services.h
Labels: chains, v0.9.6

#692 Fix potentially empty chain output when first detection service output is empty
  src/services.h
Labels: chains, v0.9.6

#681 sane behavior if trt engine filename does not end with max_batch_size
  src/backends/tensorrt/tensorrtlib.cc
  src/backends/tensorrt/tensorrtlib.h
Labels: tensorrt, v0.9.6

#668 learning rate dropout API, see 1912.00144
  src/backends/caffe/caffelib.cc
Labels: v0.9.6

#686 this PR add some cleanups on caffe detection code
  src/backends/caffe/caffelib.cc
  src/backends/caffe/caffelib.h
Labels: v0.9.6

#690 Fixed inversion of ymin and ymax in detection models output
  src/backends/caffe/caffelib.cc
  src/backends/ncnn/ncnnlib.cc
  src/backends/tensorrt/tensorrtlib.cc
  src/chain_actions.cc
Labels: API, Caffe, bug, images, v0.9.6

#673 bert + gpt2 inference + training wrt torch 1.3.1 and transformers 2.2.1
  CMakeLists.txt
  demo/gpt2/dd_client.py
  demo/gpt2/run_gpt2.py
  patches/pytorch/pytorch_compile.patch
  patches/pytorch/pytorch_logging.patch
  src/backends/torch/torchinputconns.cc
  src/backends/torch/torchinputconns.h
  src/backends/torch/torchlib.cc
  src/backends/torch/torchlib.h
  src/backends/torch/torchmodel.cc
  src/backends/torch/torchmodel.h
  src/txtinputfileconn.cc
  src/txtinputfileconn.h
  tests/CMakeLists.txt
  tests/ut-torchapi.cc
  tools/torch/README.md
  tools/torch/trace_pytorch_transformers.py
Labels: v0.9.6

#683 tensort RT 7 + OSS
  CMakeLists.txt
  README.md
Labels: tensorrt, v0.9.6
