Repository jolibrain/deepdetect, pull requests merged in 2021-02, with the labels that each got.

#1153 fix(ncnn): update innerproduct so that it does not pack data
  CMakeLists.txt
  patches/ncnn/ncnn_cont_indic.patch
  patches/ncnn/ncnn_inner_keep_h.patch
  tests/CMakeLists.txt
  tests/ut-ncnnapi.cc
Labels: mllib:NCNN, process:ready-to-review

#1159 fix(torch): gather torchscript model parameters correctly
  src/backends/torch/torchutils.cc
  src/backends/torch/torchutils.h
Labels: mllib:pytorch, process:ready-to-review

#1164 fix(csvts): throw proper error when a csv file is passed at training …
  src/csvtsinputfileconn.cc
  src/csvtsinputfileconn.h
Labels: datatype:timeseries, kind:connectors, process:ready-to-review

#1165 chore: reduce torch test acc threshold
  tests/ut-torchapi.cc
Labels: mllib:pytorch, process:ready-to-review

#1154 feat: CSV parser support for quotes and string labels
  docs/api.md
  src/backends/caffe/caffeinputconns.cc
  src/csvinputfileconn.cc
  src/csvinputfileconn.h
  src/utils/csv_parser.hpp
Labels: datatype:csv, process:merge-queued, process:ready-to-review

#1156 fix: -Werror=deprecated-copy gcc 9.3
  src/apidata.cc
  src/apidata.h
  src/jsonapi.cc
  src/mlmodel.h
  tests/ut-apidata.cc
  tests/ut-conn.cc
Labels: process:no-need-review, process:ready-to-review

#1167 ci: automatically remove process:merge-queued label
  .mergify.yml
Labels: ci:skip-tests

#1148 chore(torch): push bounds for pytorch test
  tests/ut-torchapi.cc
Labels: ci:full-build, mllib:pytorch, process:merge-queued, process:ready-to-review

#1166 build(docker): don't install system protobuf
  docker/cpu.Dockerfile
  docker/gpu.Dockerfile
  docker/gpu_tensorrt.Dockerfile
Labels: ci:docker, ci:skip-tests

#1168 fix(csvts): read from memory
  src/csvtsinputfileconn.cc
  src/csvtsinputfileconn.h
  tests/ut-torchapi.cc
Labels: datatype:timeseries, kind:connectors, process:merge-queued, process:ready-to-review

#1170 chore: improved model logger output
  src/mlmodel.h
Labels: process:merge-queued, process:ready-to-review

#1116 refactor: move /info input/ouput to oatpp::dto
  src/http/controller.hpp
  src/http/dto/info.hpp
  src/oatppjsonapi.cc
  tests/ut-oatpp.cc
  tests/ut-oatpp.h
Labels: kind:httpserver, process:merge-queued, process:ready-to-review

#1169 fix: prevent softmax after layer extraction
  src/backends/torch/torchlib.cc
Labels: mllib:pytorch, process:merge-queued, process:ready-to-review, type:bug

#1173 fix(torch): add error message when repository contains multiple models
  src/backends/torch/torchmodule.cc
Labels: mllib:pytorch, process:ready-to-review

#1174 chore: more logging in torch csvts connector
  src/backends/torch/torchinputconns.cc
Labels: kind:connectors, mllib:pytorch, process:merge-queued, process:ready-to-review

#1175 feat(bench): Add parameters for torch image backend
  clients/python/dd_client/bench.py
Labels: ci:skip-tests, client:python, process:ready-to-review

#1146 feat: use oatpp::DTO to parse img-input-connector APIData
  src/apidata.h
  src/dto/img_connector.hpp
  src/imginputfileconn.h
Labels: kind:dto, process:ready-to-review

#1176 fix(torch/txt): correctly handle test sets in case of no splitting
  src/txtinputfileconn.h
  tests/ut-torchapi.cc
Labels: datatype:text, mllib:pytorch, process:merge-queued, process:ready-to-review, type:bug

#1181 chore(torch): define explicit assignment operators
  src/backends/torch/native/templates/nbeats.h
  src/backends/torch/native/templates/vit.h
Labels: ci:multi-gpu-tests, kind:C++, mllib:pytorch, process:merge-queued, process:ready-to-review

#1183 fix(client): Change python package name to dd_client
  clients/python/setup.cfg
Labels: ci:skip-tests, client:python, process:ready-to-review

#1149 temporal transformer
  docs/api.md
  src/CMakeLists.txt
  src/backends/torch/native/native_factory.cc
  src/backends/torch/native/native_factory.h
  src/backends/torch/native/templates/ttransformer.cc
  src/backends/torch/native/templates/ttransformer.h
  src/backends/torch/native/templates/ttransformer/positionalenc.cc
  src/backends/torch/native/templates/ttransformer/positionalenc.h
  src/backends/torch/native/templates/ttransformer/tdecoder.cc
  src/backends/torch/native/templates/ttransformer/tdecoder.h
  src/backends/torch/native/templates/ttransformer/tembedder.cc
  src/backends/torch/native/templates/ttransformer/tembedder.h
  src/backends/torch/native/templates/ttransformer/tencoder.cc
  src/backends/torch/native/templates/ttransformer/tencoder.h
  src/backends/torch/native/templates/ttransformer/ttypes.h
  src/backends/torch/torchmodule.cc
  tests/ut-torchapi.cc
Labels: datatype:timeseries, mllib:pytorch, process:merge-queued, process:ready-to-review

#1180 feat(torch/txt): display msg if vocab not found
  src/txtinputfileconn.cc
Labels: datatype:text, mllib:pytorch, process:merge-queued, process:ready-to-review

#1184 fix: typo in oatpp chain HTTP endpoint
  src/http/controller.hpp
Labels: kind:chains, kind:httpserver, process:ready-to-review

#1186 feat(nbeats): add parameter coefficient to backcast loss
  src/backends/torch/native/native_factory.cc
  src/backends/torch/native/templates/nbeats.h
Labels: kind:model, mllib:pytorch, process:ready-to-review

#1187 fix: action cv macros with opencv >= 3
  src/chain_actions.cc
Labels: build:compilation, kind:chains, process:ready-to-review

#1188 fix: docker /opt/models permissions
  docker/cpu.Dockerfile
  docker/gpu.Dockerfile
Labels: ci:docker, kind:docker, process:ready-to-review

#1191 fix(torch/ranger): allow not to use lookahead
  src/backends/torch/optim/ranger.cc
Labels: kind:optimizers, mllib:pytorch, process:merge-queued, process:ready-to-review

#1179 build: set PROTOBUF_INCLUDE_DIR for pytorch
  CMakeLists.txt
  ci/devel.Dockerfile
Labels: ci:docker, ci:skip-tests

#1198 ci(docker): always build all images
  ci/Jenkinsfile.docker
Labels: ci:skip-tests, process:ready-to-review

#1200 fix(docker): ensure pip3 is working on all images
  ci/Jenkinsfile.docker
  docker/cpu.Dockerfile
  docker/gpu.Dockerfile
  docker/gpu_tensorrt.Dockerfile
Labels: ci:docker, ci:skip-tests, process:ready-to-review

#1192 feat(torch): add inference for torch detection models
  src/backends/torch/torchinputconns.cc
  src/backends/torch/torchinputconns.h
  src/backends/torch/torchlib.cc
  src/backends/torch/torchlib.h
  tests/CMakeLists.txt
  tests/ut-torchapi.cc
  tools/torch/trace_torchvision.py
Labels: kind:model, mllib:pytorch, process:merge-queued, process:ready-to-review

#1194 fix(torch/timeseries): in case of db, correctly finalize db
  src/backends/torch/torchdataset.cc
  src/backends/torch/torchinputconns.cc
  src/backends/torch/torchinputconns.h
  tests/ut-torchapi.cc
Labels: datatype:timeseries, mllib:pytorch, process:merge-queued, process:ready-to-review

#1196 fix(caffe/cudnn): force default engine option in case of cudnn not compiled in
  src/backends/caffe/caffelib.cc
  src/backends/caffe/caffelib.h
Labels: kind:cudnn, mllib:caffe, process:merge-queued, process:ready-to-review

#1197 refactor(torch): remove redundant code
  src/backends/torch/torchdataset.cc
  src/backends/torch/torchdataset.h
  src/backends/torch/torchinputconns.cc
Labels: kind:C++, mllib:pytorch, process:merge-queued, process:ready-to-review
