Repository jolibrain/deepdetect, pull requests merged in 2021-08, with the labels that each got.

#1322 chore: use default torchvision for trace_torchvision
  tools/torch/trace_torchvision.py
Labels: mllib:pytorch, process:ready-to-review, ci:skip-tests

#1323 feat(trt): add return cv::Mat instead of vector for GAN output
  src/backends/tensorrt/tensorrtlib.cc
  src/chain.cc
  src/dto/output_connector.hpp
  src/unsupervisedoutputconnector.h
Labels: datatype:images, mllib:tensorrt, process:ready-to-review

#1326 fix(test): tar archive was decompressed at each cmake call
  tests/CMakeLists.txt
Labels: build:compilation, process:ready-to-review

#1328 test(chain): add tests for chains
  tests/CMakeLists.txt
  tests/ut-chain.cc
Labels: kind:chains, process:ready-to-review, process:merge-queued

#1327 fix: torch build with custom spdlog and C++14
  CMakeLists.txt
Labels: build:compilation, mllib:pytorch, process:ready-to-review, ci:full-build

#1330 feat(dto): add custom dto vector type
  src/CMakeLists.txt
  src/dto/ddtypes.cc
  src/dto/ddtypes.hpp
  src/dto/gpuid.hpp
  src/dto/mllib.hpp
  src/utils/oatpp.cc
  tests/CMakeLists.txt
  tests/ut-dto.cc
Labels: process:ready-to-review, ci:full-build, process:merge-queued, kind:dto
