Repository jolibrain/deepdetect, pull requests merged in 2021-03, with the labels that each got.

#1202 fix: caffe build spdlog dependency
  CMakeLists.txt
Labels: build:compilation, mllib:caffe, process:ready-to-review

#1205 ci: increase time of dd bootup
  ci/build-docker-images.sh
Labels: ci:skip-tests, process:no-need-review

#1206 ci: remove unused images
  ci/build-docker-images.sh
Labels: ci:skip-tests, process:merge-queued, process:no-need-review

#1199 ci: add some documentation
  ci/README.md
  docs/ci.md
Labels: ci:skip-tests, process:merge-queued, process:ready-to-review

#1193 docs(torch): add a dedicated section for torch templates
  docs/api.md
Labels: ci:skip-tests, kind:documentation, mllib:pytorch, process:merge-queued, process:ready-to-review

#1204 feat: SSD MAP-x threshold control
  docs/api.md
  src/backends/caffe/caffelib.cc
Labels: mllib:caffe, process:merge-queued, process:ready-to-review

#1189 feat(torch): Sharpness Aware Minimization (2010.01412)
  docs/api.md
  src/CMakeLists.txt
  src/backends/torch/torchlib.cc
  src/backends/torch/torchloss.cc
  src/backends/torch/torchloss.h
  src/backends/torch/torchsolver.cc
  src/backends/torch/torchsolver.h
  tests/ut-graph.cc
  tests/ut-torchapi.cc
Labels: kind:optimizers, mllib:pytorch, process:merge-queued, process:ready-to-review

#1207 ci(docker): dont mark build as fail because of missing tensorflow image
  ci/Jenkinsfile.docker
Labels: ci:skip-tests, process:no-need-review, process:ready-to-review

#1209 ci: fix the stop button of docker images build
  ci/Jenkinsfile.docker
Labels: ci:skip-tests, process:no-need-review, process:ready-to-review

#1208 chore(torch/temporal_transformer): add explicit assignment operator f…
  src/backends/torch/native/templates/ttransformer.h
  src/backends/torch/native/templates/ttransformer/positionalenc.h
  src/backends/torch/native/templates/ttransformer/tdecoder.h
  src/backends/torch/native/templates/ttransformer/tembedder.h
  src/backends/torch/native/templates/ttransformer/tencoder.h
Labels: build:compilation, datatype:timeseries, mllib:pytorch, process:merge-queued, process:ready-to-review

#1212 ci: add jetson nano Jenkins job
  ci/Jenkinsfile-jetson-nano.unittests
  ci/README.md
  ci/devel-jetson-nano.Dockerfile
  ci/gitconfig
Labels: ci:embedded

#1211 ci(docs): add section about slave nodes
  ci/README.md
Labels: ci:skip-tests, process:merge-queued, process:ready-to-review

#1215 ci(nano): install less packages
  ci/devel-jetson-nano.Dockerfile
Labels: ci:embedded

#1217 ci: on jetson cuda need the container to be started as root
  ci/Jenkinsfile-jetson-nano.unittests
Labels: ci:embedded

#1210 fix(caffe/detection): fix rare spurious detection decoding, see bug 1190
  src/backends/caffe/caffelib.cc
Labels: mllib:caffe, process:merge-queued, process:ready-to-review, type:bug

#1223 ci: add jetson nano deviceQuery
  ci/Jenkinsfile-jetson-nano.unittests
  ci/devel-jetson-nano.Dockerfile
  ci/deviceQuery
Labels: ci:embedded

#1214 fix: tensorrt tests on Jetson nano
  tests/ut-tensorrtapi.cc
Labels: ci:embedded, mllib:tensorrt, process:ready-to-review

#1228 chore: changed my username
  .mergify.yml
Labels: ci:skip-tests

#1226 ci(docker): add new python typing_extensions dependency
  docker/cpu.Dockerfile
  docker/gpu.Dockerfile
  docker/gpu_tensorrt.Dockerfile
Labels: ci:docker, ci:skip-tests

#1213 feat(timeseries): add MAE and MSE metrics
  docs/api.md
  src/backends/caffe/caffelib.cc
  src/backends/ncnn/ncnninputconns.h
  src/backends/torch/torchlib.cc
  src/csvinputfileconn.h
  src/csvtsinputfileconn.h
  src/supervisedoutputconnector.h
  tests/ut-torchapi.cc
Labels: datatype:timeseries, process:merge-queued, process:ready-to-review

#1224 feat(nbeats): default backcast loss coeff to zero, allows very short …
  src/backends/torch/native/native_factory.cc
  src/backends/torch/native/templates/nbeats.h
  tests/ut-torchapi.cc
Labels: datatype:timeseries, mllib:pytorch, process:merge-queued, process:ready-to-review

#1232 docs: update for ubuntu 20.04
  docs/source.md
Labels: ci:skip-tests, process:merge-queued, process:ready-to-review

#1201 feat(torch/csvts): create db incrementally
  src/backends/torch/torchdataset.cc
  src/backends/torch/torchdataset.h
  src/backends/torch/torchinputconns.cc
  src/backends/torch/torchinputconns.h
  src/csvtsinputfileconn.cc
  src/csvtsinputfileconn.h
Labels: datatype:timeseries, mllib:pytorch, process:merge-queued, process:ready-to-review

#1234 fix: docker cpu link in readme
  README.md
Labels: ci:skip-tests, process:ready-to-review

#1235 ci: remove myself from ping list
  .mergify.yml
Labels: ci:skip-tests, process:no-need-review

#1236 fix(torch): display msg if resume fails, also fails if not best_model…
  src/backends/torch/torchsolver.cc
  tests/ut-torchapi.cc
Labels: mllib:pytorch, process:ready-to-review

#1237 feat(torch): save last model at training service interruption
  src/backends/torch/torchlib.cc
Labels: mllib:pytorch, process:merge-queued, process:ready-to-review

#1238 fix: compile flags typo
  src/dd_config.h.in
  src/deepdetect.cc
  src/http/dto/info.hpp
  src/jsonapi.cc
Labels: build:compilation, process:ready-to-review

#1230 fix(nbeats): make seasonality block work
  docs/api.md
  src/backends/torch/native/native_factory.cc
  src/backends/torch/native/templates/nbeats.cc
  src/backends/torch/native/templates/nbeats.h
  tests/ut-torchapi.cc
Labels: datatype:timeseries, mllib:pytorch, process:ready-to-review

#1240 feat(torch): model publishing with the platform
  src/backends/torch/torchlib.cc
  src/backends/torch/torchmodel.cc
  src/backends/torch/torchmodel.h
Labels: kind:API, mllib:pytorch, process:merge-queued, process:ready-to-review

#1231 feat(timeseries): do not output per serie metrics as a default, add p…
  docs/api.md
  src/supervisedoutputconnector.h
  tests/ut-caffeapi.cc
  tests/ut-graph.cc
  tests/ut-torchapi.cc
Labels: datatype:timeseries, kind:API, process:merge-queued, process:ready-to-review

#1239 chore(build): cpu docker with torch
  build.sh
  ci/Jenkinsfile.docker
  ci/README.md
  ci/build-docker-images.sh
  docker/README.md
  docker/cpu.Dockerfile
Labels: ci:docker, process:merge-queued, process:ready-to-review

#1241 fix(torch): throw error if multiple models are provided
  src/backends/torch/torchlib.cc
Labels: kind:API, mllib:pytorch, process:merge-queued, process:ready-to-review

#1227 SWA
  docs/api.md
  src/backends/torch/optim/ranger.cc
  src/backends/torch/optim/ranger.h
  src/backends/torch/torchlib.cc
  src/backends/torch/torchsolver.cc
  src/backends/torch/torchsolver.h
Labels: kind:optimizers, mllib:pytorch, process:merge-queued, process:ready-to-review

#1244 test(torch): tests for publishing a model and multiple models initial…
  tests/ut-torchapi.cc
Labels: mllib:pytorch, process:merge-queued, process:ready-to-review
