Repository jolibrain/deepdetect, pull requests merged in 2021-05, with the labels that each got.

#1274 feat(ml): Visformer architecture with torch backend
  docs/api.md
  src/CMakeLists.txt
  src/backends/torch/native/native_factory.cc
  src/backends/torch/native/native_factory.h
  src/backends/torch/native/templates/visformer.cc
  src/backends/torch/native/templates/visformer.h
  tests/ut-torchapi.cc
Labels: datatype:images, kind:neural net, mllib:pytorch, process:merge-queued, process:ready-to-review

#1275 fix(doc): api traced models list
  docs/api.md
Labels: ci:skip-tests, kind:documentation

#1276 feat(ml): data augmentation for object detection with torch backend
  src/backends/torch/torchdataaug.cc
  src/backends/torch/torchdataaug.h
  src/backends/torch/torchdataset.cc
  src/backends/torch/torchdataset.h
  src/backends/torch/torchinputconns.h
  src/backends/torch/torchlib.cc
Labels: datatype:data augmentation, datatype:images, mllib:pytorch, process:merge-queued, process:ready-to-review

#1247 fix: moving back to FAISS master
  CMakeLists.txt
  src/simsearch.cc
Labels: build:compilation, mllib:simsearch, process:merge-queued, process:ready-to-review

#1281 chore(tensorrt): update to c++ 14
  CMakeLists.txt
  patches/trt/0003-c++14.patch
Labels: mllib:tensorrt, process:merge-queued, process:ready-to-review

#1269 refactor(torch): torch init to DTO
  src/CMakeLists.txt
  src/apidata.h
  src/backends/torch/torchlib.cc
  src/dto/gpuid.cc
  src/dto/gpuid.hpp
  src/dto/mllib.hpp
  src/http/app_component.hpp
  src/oatppjsonapi.cc
  src/utils/oatpp.cc
  src/utils/oatpp.hpp
  tests/ut-torchapi.cc
Labels: kind:dto, mllib:pytorch, process:merge-queued, process:ready-to-review

#1278 refactor(tensorrt) : predict to dto
  src/backends/tensorrt/tensorrtlib.cc
  src/dto/output_connector.hpp
Labels: kind:dto, mllib:tensorrt, process:merge-queued, process:ready-to-review

#1286 fix(build): torch 1.8 with cuda 11.3 string_view patch
  CMakeLists.txt
  patches/pytorch/pytorch_18_string_view.patch
Labels: build:compilation, ci:full-build, mllib:pytorch, process:merge-queued, process:ready-to-review

#1288 chore(build): single location for lmdb C++ wrapper
  CMakeLists.txt
  src/CMakeLists.txt
  src/backends/torch/torchdataset.h
  src/simsearch.cc
  src/simsearch.h
  src/utils/db.cpp
  src/utils/db.hpp
  src/utils/db_lmdb.cpp
  src/utils/db_lmdb.hpp
Labels: mllib:simsearch, process:merge-queued, process:ready-to-review

#1289 feat(ml): python script to trace timm vision models
  tools/torch/trace_timm_models.py
Labels: ci:skip-tests, mllib:pytorch, process:ready-to-review

#1290 feat(build): CMake config file to link with dede
  CMakeLists.txt
  cmake/DeepDetectConfig.cmake.in
Labels: build:compilation, ci:skip-tests, process:merge-queued, process:ready-to-review

#1292 chore(cmake): change ddconfig variables names to be more consistent
  cmake/DeepDetectConfig.cmake.in
Labels: ci:skip-tests, process:no-need-review

#1285 Torch multigpu V2
  src/backends/torch/native/native_net.h
  src/backends/torch/native/native_wrapper.h
  src/backends/torch/torchlib.cc
  src/backends/torch/torchloss.h
  src/backends/torch/torchmodule.cc
  src/backends/torch/torchmodule.h
  src/backends/torch/torchsolver.cc
  src/backends/torch/torchsolver.h
  src/backends/torch/torchutils.cc
  src/backends/torch/torchutils.h
  src/utils/utils.hpp
  tests/ut-torchapi.cc
Labels: ci:multi-gpu-tests, kind:GPU, mllib:pytorch, process:ready-to-review

#1296 fix(build): add required definitions and include directory for buildi…
  CMakeLists.txt
  cmake/DeepDetectConfig.cmake.in
Labels: process:merge-queued, process:ready-to-review

#1295 chore: always activate multigpu tests
  ci/Jenkinsfile.unittests
Labels: mllib:pytorch, process:merge-queued, process:ready-to-review

#1293 chore(build): torch 1.8.1 and torchvision 0.9.1
  CMakeLists.txt
Labels: build:compilation, ci:full-build, mllib:pytorch, process:merge-queued, process:ready-to-review
