Repository jolibrain/deepdetect, pull requests merged in 2021-04, with the labels that each got.

#1246 feat(torch): add confidence threshold for classification
  src/backends/torch/torchlib.cc
  tests/ut-torchapi.cc
Labels: kind:API, mllib:pytorch, process:ready-to-review

#1249 fix: remove dirty git flag on builds
  CMakeLists.txt
Labels: build:compilation, process:merge-queued, process:ready-to-review

#1250 fix(timeseries): throw if no data found
  src/csvtsinputfileconn.cc
Labels: datatype:timeseries, process:merge-queued, process:ready-to-review

#1251 fix(torch): Fix underflow in CSVTS::serialize_bounds
  src/csvtsinputfileconn.cc
Labels: kind:connectors, mllib:pytorch, process:merge-queued, process:ready-to-review, type:bug

#1248 feat(torch): allow FP16 inference on GPU
  docs/api.md
  src/backends/torch/torchlib.cc
  src/backends/torch/torchlib.h
  src/backends/torch/torchmodule.cc
  src/backends/torch/torchmodule.h
  src/backends/torch/torchutils.cc
  tests/ut-torchapi.cc
Labels: mllib:pytorch, process:merge-queued, process:ready-to-review

#1253 fix(ml): refinedet image dimensions configuration via API
  src/backends/caffe/caffelib.cc
Labels: datatype:images, mllib:caffe, process:ready-to-review

#1203 feat(torch): torch detection training
  CMakeLists.txt
  docs/api.md
  patches/pytorch/vision/pytorch_vision_09_fasterrcnn.patch
  src/backends/torch/torchdataset.cc
  src/backends/torch/torchdataset.h
  src/backends/torch/torchinputconns.cc
  src/backends/torch/torchinputconns.h
  src/backends/torch/torchlib.cc
  src/backends/torch/torchlib.h
  src/backends/torch/torchloss.cc
  src/backends/torch/torchloss.h
  src/backends/torch/torchmodule.cc
  src/backends/torch/torchmodule.h
  src/utils/bbox.hpp
  tests/CMakeLists.txt
  tests/ut-torchapi.cc
  tools/torch/trace_torchvision.py
Labels: datatype:images, kind:model, mllib:pytorch, process:ready-to-review

#1243 fix(torch): allow partial or mismatching weights loading only if fine…
  src/backends/torch/torchlib.cc
  src/backends/torch/torchmodule.cc
  src/backends/torch/torchmodule.h
  src/backends/torch/torchutils.cc
  src/backends/torch/torchutils.h
  tests/ut-torchapi.cc
Labels: mllib:pytorch, process:ready-to-review

#1252 madgrad
  docs/api.md
  src/CMakeLists.txt
  src/backends/torch/optim/madgrad.cc
  src/backends/torch/optim/madgrad.h
  src/backends/torch/torchsolver.cc
  src/backends/torch/torchsolver.h
  tests/ut-torchapi.cc
Labels: kind:optimizers, mllib:pytorch, process:merge-queued, process:ready-to-review

#1255 fix(torch): default gradient clipping to true when using madgrad
  src/backends/torch/torchsolver.cc
Labels: kind:optimizers, mllib:pytorch, process:ready-to-review

#1256 fix(chains): cloning of image crops in chains
  src/chain_actions.cc
Labels: datatype:images, kind:chains, process:merge-queued, process:ready-to-review, type:bug

#1254 feat(torch): add more backbones to traced detection models
  tools/torch/trace_torchvision.py
Labels: kind:model, mllib:pytorch, process:merge-queued, process:ready-to-review

#1258 fix(torch): parameters are added only once to solver during training
  src/backends/torch/torchutils.cc
Labels: mllib:pytorch, process:merge-queued, process:ready-to-review, type:bug

#1259 fix(torch): select correct mltype
  src/backends/torch/torchlib.cc
Labels: mllib:pytorch, process:merge-queued, process:ready-to-review

#1257 fix(torch): fix very long ETA with iter_size != 1
  src/backends/torch/torchlib.cc
Labels: mllib:pytorch, process:merge-queued, process:ready-to-review

#1262 fix(TensorRT): fix some memory fragmentation weirdness in trt backend
  CMakeLists.txt
  src/backends/tensorrt/tensorrtlib.cc
  src/backends/tensorrt/tensorrtlib.h
Labels: mllib:tensorrt, process:ready-to-review

#1263 fix: services names were not always case insensitive
  src/jsonapi.cc
  src/jsonapi.h
  tests/ut-oatpp.cc
Labels: process:merge-queued, process:ready-to-review, type:bug

#1266 chore(client): fix dd client formatting
  clients/python/dd_client/__init__.py
Labels: ci:skip-tests, client:python, process:no-need-review

#1265 fix(torch): fix faster rcnn model export for training
  tools/torch/trace_torchvision.py
Labels: kind:model, mllib:pytorch, process:merge-queued, process:ready-to-review

#1245 refactor(dto): ncnn init and generic dto objects
  src/apidata.h
  src/backends/ncnn/ncnnlib.cc
  src/backends/ncnn/ncnnlib.h
  src/backends/ncnn/ncnnmodel.h
  src/dto/info.hpp
  src/dto/input_connector.hpp
  src/dto/mllib.hpp
  src/dto/model.hpp
  src/dto/output_connector.hpp
  src/dto/parameters.hpp
  src/dto/service_create.hpp
  src/http/controller.hpp
  src/http/dto/info.hpp
  src/imginputfileconn.h
  src/supervisedoutputconnector.h
Labels: kind:dto, mllib:NCNN, process:merge-queued, process:ready-to-review

#1267 feat(torch): add batch size > 1 for detection models
  src/backends/torch/torchdataset.cc
  src/backends/torch/torchdataset.h
  src/backends/torch/torchinputconns.h
  src/backends/torch/torchlib.cc
  tests/CMakeLists.txt
  tests/ut-torchapi.cc
  tools/torch/trace_torchvision.py
Labels: kind:model, mllib:pytorch, process:merge-queued, process:ready-to-review

#1270 fix(torch): retinanet now trains correctly
  tools/torch/trace_torchvision.py
Labels: ci:skip-tests, kind:model, mllib:pytorch, process:merge-queued, process:ready-to-review

#1268 refactor(ncnn): predict to DTO
  src/backends/ncnn/ncnnlib.cc
  src/dto/service_predict.hpp
Labels: kind:dto, mllib:NCNN, process:merge-queued, process:ready-to-review

#1264 fix(torch): torchvision models can be used with grayscale images
  src/backends/torch/native/native_factory.h
  src/backends/torch/torchdataset.cc
  src/backends/torch/torchinputconns.h
  src/backends/torch/torchlib.cc
  tests/ut-torchapi.cc
Labels: datatype:images, kind:connectors, mllib:pytorch, process:merge-queued, process:ready-to-review

#1272 feat(torch): image data augmentation with random geometric perspectives
  src/backends/torch/torchdataaug.cc
  src/backends/torch/torchdataaug.h
  src/backends/torch/torchlib.cc
  tests/ut-torchapi.cc
Labels: datatype:data augmentation, datatype:images, mllib:pytorch, process:merge-queued, process:ready-to-review

#1273 fix(graph): loading weights from previous model does not fail
  src/backends/torch/torchlib.cc
  tests/ut-graph.cc
Labels: mllib:pytorch, process:ready-to-review, type:bug
