Repository jolibrain/deepdetect, pull requests merged in 2021-01, with the labels that each got.

#1110 fix: refinedet vovnet deploy parameter setup
  src/backends/caffe/caffelib.cc
Labels: datatype:images, kind:neural net, mllib:caffe, process:ready-to-review

#1109 fix: NCNN best parameter for classification models
  src/backends/ncnn/ncnnlib.cc
  src/backends/ncnn/ncnnmodel.cc
  tests/CMakeLists.txt
  tests/ut-ncnnapi.cc
Labels: mllib:NCNN, process:merge-queued, process:ready-to-review

#1107 ml: torch ViT small and tiny models as in https://arxiv.org/abs/201212877
  src/backends/torch/native/templates/vit.cc
Labels: datatype:images, kind:neural net, mllib:pytorch, process:ready-to-review

#1104 test(torch): add tests for native weights loading
  tests/CMakeLists.txt
  tests/ut-torchapi.cc
Labels: ci:no-datasets-cache, mllib:pytorch, process:merge-queued, process:ready-to-review

#1114 Fix NCNN bbox loop + Add datatype fp32/fp16 control to NCNN backend inference
  src/backends/ncnn/ncnnlib.cc
  tests/ut-ncnnapi.cc
Labels: mllib:NCNN, process:ready-to-review

#1106 fix: wrong template_params with torch from DD API
  docs/api.md
  src/backends/torch/native/native_factory.cc
  src/backends/torch/torchlib.cc
  tests/ut-torchapi.cc
Labels: kind:API, mllib:pytorch, process:merge-queued, process:ready-to-review

#1112 test(torch): Make some tests deterministic
  tests/ut-torchapi.cc
Labels: mllib:pytorch, process:merge-queued, process:ready-to-review

#1118 fix: pass CUDA_ARCH correctly to caffe
  CMakeLists.txt
Labels: process:ready-to-review

#1092 ci: allow to disable boost::stacktrace
  CMakeLists.txt
  src/httpjsonapi.cc
  src/oatppjsonapi.cc
Labels: process:ready-to-review

#1121 fix: copy .git in docker image builder
  .dockerignore
Labels: process:merge-queued, process:ready-to-review

#1123 fix(doc): similarity search_nn number of results API
  docs/api.md
Labels: ci:skip-tests, kind:documentation, process:merge-queued, process:ready-to-review

#1125 docs(docker): make sharing volume slightly clearer
  docs/docker.md
Labels: ci:skip-tests, kind:documentation, process:merge-queued, process:ready-to-review

#1128 feat(ml): retain_graph control via API for torch autograd
  docs/api.md
  src/backends/torch/torchlib.cc
Labels: kind:API, mllib:pytorch, process:merge-queued, process:ready-to-review

#1124 fix(torch): remove potential segfault in csvts connector
  src/backends/torch/torchinputconns.cc
Labels: kind:connectors, mllib:pytorch, process:merge-queued, process:ready-to-review

#1130 fix: caffe linkage with our spdlog
  CMakeLists.txt
Labels: ci:skip-tests, process:merge-queued, process:ready-to-review

#1131 fix: add missing spdlog patch
  patches/spdlog/1818.patch
Labels: process:merge-queued, process:no-need-review

#1103 ncnn master
  CMakeLists.txt
  patches/ncnn/ncnn_flatten_axis.patch
  patches/ncnn/ncnn_inner_keep_h.patch
  patches/ncnn/ncnn_lstm_cont.patch
  patches/ncnn/ncnn_variable_h.patch
  src/backends/ncnn/caffe2ncnn.cc
  src/backends/ncnn/ncnninputconns.h
  src/backends/ncnn/ncnnlib.cc
  tests/ut-ncnnapi.cc
Labels: ci:full-build, mllib:NCNN, process:merge-queued, process:ready-to-review

#1132 fix: throw if hard image read error in caffe classification input
  src/backends/caffe/caffeinputconns.cc
Labels: datatype:images, mllib:caffe, process:merge-queued, process:ready-to-review

#1133 chore: upgrade spdlog to 1.8.2
  CMakeLists.txt
  patches/spdlog/1818.patch
Labels: process:no-need-review

#1135 chore: add link to docker image tags
  README.md
Labels: ci:skip-tests, process:no-need-review

#1137 fix: NCNN chain with images and actions
  src/backends/ncnn/ncnnlib.cc
Labels: datatype:images, kind:chains, mllib:NCNN, process:ready-to-review

#1140 chore: bump torchvision to 0.8.2
  CMakeLists.txt
Labels: build:compilation, kind:model, kind:neural net, mllib:pytorch, process:merge-queued, process:ready-to-review

#1139 fix: missing support for parent_id in chains with Python client
  clients/python/dd_client/__init__.py
Labels: ci:skip-tests, client:python, kind:chains, process:merge-queued, process:ready-to-review

#1144 ci: disable multi gpus by default
  ci/Jenkinsfile.unittests
Labels: ci:skip-tests, process:merge-queued, process:no-need-review

#1143 chore: bump torch tests eucll assertion
  tests/ut-torchapi.cc
Labels: mllib:pytorch, process:merge-queued, process:ready-to-review

#1122 Basic image data augmentation for the torch backend
  src/CMakeLists.txt
  src/backends/torch/torchdataaug.cc
  src/backends/torch/torchdataaug.h
  src/backends/torch/torchdataset.cc
  src/backends/torch/torchdataset.h
  src/backends/torch/torchinputconns.cc
  src/backends/torch/torchlib.cc
  tests/ut-torchapi.cc
Labels: datatype:data augmentation, datatype:images, mllib:pytorch, process:merge-queued, process:ready-to-review

#1136 fix: deactivate the csvts NCNN test when caffe is not built
  CMakeLists.txt
  tests/ut-ncnnapi.cc
Labels: mllib:NCNN, process:merge-queued, process:ready-to-review

#1142 fix(torch): csvts forecast mode needs sequence of length backcast dur…
  src/backends/torch/torchinputconns.cc
Labels: kind:connectors, mllib:pytorch, process:merge-queued, process:ready-to-review

#1138 feat: support for batches for NCNN image models
  src/backends/ncnn/ncnninputconns.h
  src/backends/ncnn/ncnnlib.cc
  tests/ut-ncnnapi.cc
Labels: ci:full-build, datatype:images, mllib:NCNN, process:merge-queued, process:ready-to-review

#1095 Multiple test sets
  src/backends/caffe/caffeinputconns.cc
  src/backends/caffe/caffeinputconns.h
  src/backends/caffe/caffelib.cc
  src/backends/torch/torchdataset.cc
  src/backends/torch/torchdataset.h
  src/backends/torch/torchinputconns.cc
  src/backends/torch/torchinputconns.h
  src/backends/torch/torchlib.cc
  src/backends/torch/torchlib.h
  src/backends/torch/torchsolver.cc
  src/backends/torch/torchsolver.h
  src/backends/xgb/xgbinputconns.cc
  src/backends/xgb/xgblib.cc
  src/csvinputfileconn.cc
  src/csvinputfileconn.h
  src/csvtsinputfileconn.cc
  src/csvtsinputfileconn.h
  src/imginputfileconn.h
  src/inputconnectorstrategy.h
  src/supervisedoutputconnector.h
  src/svminputfileconn.cc
  src/svminputfileconn.h
  src/txtinputfileconn.cc
  src/txtinputfileconn.h
  src/utils/fileops.hpp
  src/utils/utils.hpp
  tests/ut-graph.cc
  tests/ut-torchapi.cc
Labels: ci:full-build, datatype:images, datatype:text, datatype:timeseries, mllib:pytorch, process:ready-to-review

#1134 fix(build): pytorch with custom spdlog
  CMakeLists.txt
  ci/Jenkinsfile.prebuilt-cache
  ci/Jenkinsfile.unittests
  patches/pytorch/pytorch_16_new_logger.patch
  src/CMakeLists.txt
  src/backends/torch/llogging.h
Labels: ci:full-build, process:merge-queued, process:ready-to-review

#1158 fix(chore): typo when trying to use syslog
  src/dd_spdlog.h
Labels: kind:C++, process:ready-to-review

#1145 fix(torch): set seed of torchdataset during training
  src/backends/torch/torchdataset.cc
  src/backends/torch/torchdataset.h
  src/backends/torch/torchinputconns.cc
  src/backends/torch/torchinputconns.h
Labels: kind:connectors, mllib:pytorch, process:ready-to-review

#1141 feat: running custom methods from jit models
  docs/api.md
  src/backends/torch/torchlib.cc
  src/backends/torch/torchmodule.cc
  src/backends/torch/torchmodule.h
Labels: mllib:pytorch, process:ready-to-review

#1127 feat(ml): ViT support for Realformer
  docs/api.md
  src/backends/torch/native/templates/vit.cc
  src/backends/torch/native/templates/vit.h
  tests/ut-torchapi.cc
Labels: datatype:images, kind:neural net, mllib:pytorch, process:ready-to-review

#1157 fix: torch backend CPU build and tests
  src/backends/torch/torchmodule.cc
  src/backends/torch/torchmodule.h
  tests/ut-torchapi.cc
Labels: mllib:pytorch, process:ready-to-review
