Repository jolibrain/deepdetect, pull requests merged in 2021-06, with the labels that each got.

#1299 fix(chain): fixed_size crops now work at the edges of images
  src/chain_actions.cc
Labels: kind:chains, process:merge-queued, process:ready-to-review

#1298 chore(build): do not rebuild tensorrt backend upon calling make
  CMakeLists.txt
Labels: build:compilation, mllib:tensorrt, process:merge-queued, process:ready-to-review

#1297 feat(ml): inference for GAN generators with TensorRT backend
  src/backends/tensorrt/tensorrtlib.cc
  src/backends/tensorrt/tensorrtlib.h
  src/dto/mllib.hpp
  tests/CMakeLists.txt
  tests/ut-tensorrtapi.cc
Labels: datatype:images, mllib:tensorrt, process:ready-to-review

#1301 chore(ml): updated torchvision and timm model import scripts
  tools/torch/trace_timm_models.py
  tools/torch/trace_torchvision.py
Labels: ci:skip-tests, datatype:images, mllib:pytorch, process:merge-queued, process:ready-to-review

#1300 fix(build): do not rebuild tensorrt if not needed
  CMakeLists.txt
  cmake/build_external.sh
  cmake/patch_external.sh
Labels: build:compilation, ci:skip-tests, mllib:tensorrt, process:merge-queued, process:ready-to-review

#1282 chore(cuda): support for Ampere GPU builds
  build.sh
Labels: build:compilation, ci:docker, kind:docker, process:merge-queued, process:ready-to-review

#1303 chore(cmake): add missing includes to link with dd
  CMakeLists.txt
Labels: ci:skip-tests, process:merge-queued, process:ready-to-review

#1302 feat(torch): add dataloader_threads in API
  docs/api.md
  src/backends/torch/torchdataset.cc
  src/backends/torch/torchdataset.h
  src/backends/torch/torchlib.cc
  tests/ut-torchapi.cc
Labels: kind:API, mllib:pytorch, process:merge-queued, process:ready-to-review

#1305 chore(torch): set default value for dataloader thread back from 2 to 1
  src/backends/torch/torchlib.cc
Labels: mllib:pytorch, process:merge-queued, process:ready-to-review

#1304 feat(torch): support detection models in chains
  src/backends/torch/torchlib.cc
Labels: kind:chains, mllib:pytorch, process:merge-queued, process:ready-to-review

#1307 chore(build): add needed includes for linking with tensorrt dd
  CMakeLists.txt
Labels: ci:skip-tests, process:merge-queued, process:ready-to-review

#1306 feat(torch): add best for detection model inference
  docs/api.md
  src/backends/caffe/caffelib.cc
  src/backends/ncnn/ncnnlib.cc
  src/backends/tensorrt/tensorrtlib.cc
  src/backends/torch/torchlib.cc
  src/dto/output_connector.hpp
  tests/ut-torchapi.cc
Labels: kind:API, mllib:pytorch, process:merge-queued, process:ready-to-review

#1309 fix(trt): apply std to input image correctly
  src/backends/tensorrt/tensorrtinputconns.cc
  src/backends/tensorrt/tensorrtinputconns.h
Labels: kind:connectors, mllib:tensorrt, process:merge-queued, process:ready-to-review

#1310 chore: fix typo in controller
  src/http/controller.hpp
Labels: kind:C++, process:merge-queued, process:ready-to-review

#1311 fix: remove linking errors on oatpp access_log
  src/CMakeLists.txt
  src/http/access_log.cpp
  src/http/access_log.hpp
Labels: build:compilation, process:merge-queued, process:ready-to-review

#1314 chore: update oatpp to 1.2.5
  CMakeLists.txt
Labels: process:merge-queued, process:ready-to-review

#1308 feat(torch): add ADAMP variant of adam in RANGER (2006.08217)
  docs/api.md
  src/backends/torch/optim/ranger.cc
  src/backends/torch/optim/ranger.h
  src/backends/torch/torchsolver.cc
  src/backends/torch/torchsolver.h
  tests/ut-torchapi.cc
Labels: kind:optimizers, mllib:pytorch, process:merge-queued, process:ready-to-review

#1312 Znorm
  docs/api.md
  src/backends/caffe/caffelib.cc
  src/backends/ncnn/ncnninputconns.h
  src/backends/torch/torchlib.cc
  src/csvinputfileconn.cc
  src/csvinputfileconn.h
  src/csvtsinputfileconn.cc
  src/csvtsinputfileconn.h
  src/inputconnectorstrategy.h
  tests/ut-conn.cc
Labels: datatype:csv, datatype:timeseries, process:merge-queued, process:ready-to-review

#1313 feat: add DTO schemas to swagger automatic doc
  src/dto/gpuid.hpp
  src/http/controller.hpp
  src/oatppjsonapi.cc
  src/utils/oatpp.cc
Labels: kind:API, kind:documentation, process:merge-queued, process:ready-to-review
