Repository jolibrain/deepdetect, pull requests merged in 2021-11, with the labels that each got.

#1351 feat: add yolox export script for training and inference
  src/backends/torch/torchlib.cc
  tools/torch/trace_yolox.py
Labels: kind:model, mllib:pytorch, process:ready-to-review

#1364 chore: force removal of first docker trt devel
  ci/Jenkinsfile-trt.unittests
Labels: kind:docker, mllib:tensorrt, process:ready-to-review, ci:docker

#1357 chore(ci): docker tensorrt with nvcuvid
  ci/devel-trt.Dockerfile
  docker/gpu_tensorrt.Dockerfile
Labels: mllib:tensorrt, process:ready-to-review, ci:docker, ci:embedded

#1366 chore: tensorrt default build uses OpenCV4 with full CUDA pipeline
  build.sh
  ci/Jenkinsfile.docker
  ci/build-docker-images.sh
  docker/gpu_tensorrt.Dockerfile
Labels: kind:docker, mllib:tensorrt, process:ready-to-review, ci:docker

#1369 fix: simsearch ivf index craft after reload, disabling mmap
  src/simsearch.cc
Labels: mllib:simsearch, process:ready-to-review, process:merge-queued

#1365 fix: avoid crashes caused by an exception in the training loop
  src/backends/torch/torchlib.cc
  tools/torch/trace_yolox.py
Labels: type:bug, mllib:pytorch, process:ready-to-review

#1371 chore: source doc requirements update
  docs/source.md
Labels: kind:documentation, process:ready-to-review, ci:skip-tests

#1372 fix: torch train shuffles image dataset by default
  src/backends/torch/torchdataset.h
Labels: mllib:pytorch, process:ready-to-review

#1374 fix: add mltype in metrics.json even if training is not over
  src/mlservice.h
Labels: kind:API, process:ready-to-review

#1373 feat: training segmentation models with torch backend
  src/backends/torch/torchdataset.cc
  src/backends/torch/torchdataset.h
  src/backends/torch/torchinputconns.cc
  src/backends/torch/torchinputconns.h
  src/backends/torch/torchlib.cc
  src/backends/torch/torchloss.cc
  src/backends/torch/torchloss.h
  tests/CMakeLists.txt
  tests/ut-torchapi.cc
Labels: datatype:images, mllib:pytorch, process:ready-to-review

#1360 feat: add yolox onnx export and trt support
  src/backends/tensorrt/tensorrtlib.cc
  src/backends/tensorrt/tensorrtlib.h
  src/dto/output_connector.hpp
  src/imginputfileconn.h
  src/utils/bbox.hpp
  tests/CMakeLists.txt
  tests/ut-tensorrtapi.cc
  tools/torch/trace_yolox.py
Labels: kind:model, datatype:images, mllib:tensorrt, process:ready-to-review, ci:docker, ci:embedded

#1377 feat: data augmentation for training segmentation models with torch backend
  src/backends/torch/torchdataaug.cc
  src/backends/torch/torchdataaug.h
  src/backends/torch/torchdataset.cc
  src/backends/torch/torchdataset.h
  tests/ut-torchapi.cc
Labels: datatype:images, datatype:data augmentation, mllib:pytorch, process:ready-to-review
