Repository jolibrain/deepdetect, pull requests merged in 2022-02, with the labels that each got.

#1397 chore: yolox export filenames and documentation
  tools/torch/README.md
  tools/torch/trace_yolox.py
Labels: kind:model, mllib:pytorch, process:ready-to-review, ci:skip-tests, process:merge-queued

#1401 fix: caffe object detector training requires test set
  src/backends/caffe/caffeinputconns.cc
Labels: mllib:caffe, process:ready-to-review, process:merge-queued

#1402 chore: unit test datasets untar no verbosity
  tests/CMakeLists.txt
Labels: process:ready-to-review, ci:skip-tests

#1400 Fix map with torch
  src/supervisedoutputconnector.h
Labels: mllib:pytorch, process:ready-to-review

#1398 fix: torch MaP with bboxes
  src/backends/torch/torchlib.cc
Labels: mllib:pytorch, process:ready-to-review

#1403 feat: allow pure negative samples for training object detectors with torch
  src/backends/torch/torchdataset.cc
Labels: datatype:images, mllib:pytorch, process:ready-to-review, process:merge-queued

#1404 feat: random crops for object detector training with torch backend
  src/backends/torch/torchdataaug.cc
  src/backends/torch/torchdataaug.h
  src/backends/torch/torchdataset.cc
  tests/ut-torchapi.cc
Labels: datatype:data augmentation, mllib:pytorch, process:ready-to-review
