Repository jolibrain/deepdetect, pull requests merged in 2022-09, with the labels that each got.

#1457 Fix torch model behavior with best: -1
  src/backends/torch/torchlib.cc
Labels: type:bug, mllib:pytorch, process:ready-to-review, process:merge-queued

#1461 test: use a local image instead of web image
  tests/CMakeLists.txt
  tests/ut-chain.cc
Labels: type:bug, process:ready-to-review, process:merge-queued

#1459 test: add a test script to check that yolox export to tensorrt works …
  src/backends/tensorrt/tensorrtlib.cc
  tests/ut_python/ut_tools_torch.py
  tests/ut_python/ut_tools_torch_yolox.py
  tools/torch/trace_yolox.py
Labels: kind:model, mllib:tensorrt, process:ready-to-review, process:merge-queued

#1462 fix: adamw default weight decay with torch backend
  src/backends/torch/torchsolver.cc
Labels: type:bug, kind:optimizers

#1460 chore: torch 1.12.1 / torchvision 0.13.1
  CMakeLists.txt
Labels: mllib:pytorch, ci:full-build

#1465 feat(torch): allow multigpu for traced models
  src/backends/torch/torchmodule.cc
  tests/ut-torchapi.cc
Labels: kind:API, mllib:pytorch, process:ready-to-review, process:merge-queued, ci:multi-gpu-tests

#1467 feat(yolox): export directly from trained dd repo to onnx
  tools/torch/trace_yolox.py
Labels: kind:model, mllib:pytorch, process:ready-to-review, ci:skip-tests

#1464 feat(torch): best model is computed over all the test sets
  src/backends/torch/torchlib.cc
  src/backends/torch/torchlib.h
  src/backends/torch/torchsolver.cc
  src/supervisedoutputconnector.h
Labels: kind:API, mllib:pytorch, process:ready-to-review, process:merge-queued

#1466 fix(docker): add libcupti to gpu_torch docker
  docker/gpu.Dockerfile
Labels: process:ready-to-review, ci:docker

#1468 fix(oatpp): oatpp-zlib memory leak
  CMakeLists.txt
Labels: type:bug, build:compilation, kind:API, process:ready-to-review, process:merge-queued
