Repository jolibrain/deepdetect, pull requests merged in 2022-03, with the labels that each got.

#1408 fix(trt): yolox failed at second inference
  src/backends/tensorrt/tensorrtlib.cc
Labels: type:bug, kind:model, mllib:tensorrt, process:ready-to-review, process:merge-queued

#1407 fix: torch model publish crash and repository
  src/backends/torch/torchmodel.cc
Labels: type:bug, mllib:pytorch, process:ready-to-review, process:merge-queued

#1409 feat: tensorrt object detector top_k control
  src/backends/tensorrt/protoUtils.cc
  src/backends/tensorrt/protoUtils.h
  src/backends/tensorrt/tensorrtlib.cc
  src/backends/tensorrt/tensorrtlib.h
  src/dto/output_connector.hpp
Labels: mllib:tensorrt, process:ready-to-review, process:merge-queued

#1413 chore: freeze torch version for unit tests
  ci/devel-trt.Dockerfile
  ci/devel.Dockerfile
Labels: kind:packaging, process:ready-to-review, process:merge-queued

#1411 fix: cropped model input size when publishing torch models + tests
  src/backends/torch/torchmodel.cc
  tests/ut-torchapi.cc
Labels: datatype:data augmentation, mllib:pytorch, process:ready-to-review, process:merge-queued

#1414 fix: torch best model better or equal
  src/backends/torch/torchlib.cc
Labels: mllib:pytorch, process:ready-to-review, process:merge-queued

#1415 feat: sliding object detection script
  demo/objdetect/sliding_objdetect.py
Labels: client:python, process:ready-to-review, ci:skip-tests, process:merge-queued

#1410 feat(torch): bump to torch 1.11 and torchvision 0.12
  CMakeLists.txt
  ci/devel-trt.Dockerfile
  ci/devel.Dockerfile
  patches/pytorch/pytorch_19_use_new_logger.patch
  src/backends/torch/torchinputconns.h
  src/backends/torch/torchlib.cc
  src/backends/torch/torchlib.h
  src/backends/torch/torchutils.h
  tests/CMakeLists.txt
  tests/ut-torchapi.cc
  tests/ut_python/ut_tools_torch.py
Labels: mllib:pytorch, process:ready-to-review, ci:full-build, process:merge-queued
