Repository jolibrain/deepdetect, pull requests merged in 2022-12, with the labels that each got.

#1478 chore: raw image support in cv2 format for dd_client
  ci/Jenkinsfile.unittests
  clients/python/dd_client/__init__.py
  clients/python/tox.ini
Labels: client:python, ci:skip-tests, process:no-need-review, process:merge-queued

#1479 update timm extractor for last version of timm
  tools/torch/trace_timm_models.py
Labels: process:ready-to-review, ci:skip-tests, process:merge-queued

#1481 feat(torch): set data augmentation factors as requested
  src/backends/torch/torchlib.cc
Labels: type:bug, datatype:data augmentation
