Repository jolibrain/deepdetect, pull requests merged in 2022-01, with the labels that each got.

#1387 feat(bench): add monitoring of transform time
  clients/python/dd_client/bench.py
Labels: client:python, process:ready-to-review, ci:skip-tests

#1389 fix(torch): fix unweighted dice loss
  src/backends/torch/torchloss.cc
Labels: datatype:images, mllib:pytorch, process:ready-to-review

#1391 chore: update to torch 1.10.1
  CMakeLists.txt
Labels: build:compilation, mllib:pytorch, process:ready-to-review, ci:full-build

#1390 fix: segmentation with torch backend + full cropping support
  src/backends/torch/torchdataaug.cc
  src/backends/torch/torchdataaug.h
  src/backends/torch/torchdataset.cc
  src/backends/torch/torchdataset.h
  src/backends/torch/torchlib.cc
  src/backends/torch/torchloss.cc
  src/backends/torch/torchutils.h
  tests/ut-torchapi.cc
  tools/torch/trace_torchvision.py
Labels: datatype:images, mllib:pytorch, process:ready-to-review, process:merge-queued

#1392 fix: model.json file saving
  src/jsonapi.cc
Labels: type:bug, process:ready-to-review

#1393 fix: torch model published config file
  docs/api.md
  src/backends/torch/torchlib.cc
  src/backends/torch/torchmodel.cc
  src/backends/torch/torchmodel.h
  src/jsonapi.cc
  src/mlservice.h
  tests/ut-caffeapi.cc
  tests/ut-torchapi.cc
  tests/ut-xgbapi.cc
Labels: kind:model, kind:API, mllib:pytorch, process:ready-to-review, process:merge-queued

#1395 feat: segmentation of large images with sliding window, example Python script
  demo/segmentation/segment_sliding.py
Labels: client:python, datatype:images, process:ready-to-review, ci:skip-tests

#1396 feat(chain): allow chain custom actions
  src/chain_actions.cc
  src/chain_actions.h
Labels: kind:chains, process:ready-to-review, process:merge-queued

#1394 feat(chain): add action to draw bboxes as trailing action
  demo/objdetect/README.md
  demo/objdetect/chaindetect.py
  demo/objdetect/dd_client.py
  src/chain.cc
  src/chain_actions.cc
  src/chain_actions.h
  src/dto/chain.hpp
  src/dto/ddtypes.cc
  src/dto/ddtypes.hpp
  src/services.h
  src/utils/oatpp.cc
  tests/ut-chain.cc
Labels: kind:API, kind:chains, process:ready-to-review
