Repository jolibrain/deepdetect, pull requests merged in 2022-06, with the labels that each got.

#1442 fix: missing path to cub headers in tensorrt-oss build for jetson nano
  CMakeLists.txt
  patches/trt/0011-fix_plugin_makefile_cub.patch
Labels: build:compilation, process:ready-to-review, process:merge-queued, build:jetson

#1443 fix: add missing headers in predict_out.hpp
  src/dto/predict_out.hpp
Labels: process:ready-to-review, ci:skip-tests, kind:dto

#1444 fix: missing ifdef
  src/dto/predict_out.hpp
Labels: ci:skip-tests, process:no-need-review, process:merge-queued

#1445 build: allow to disable swagger
  CMakeLists.txt
  src/CMakeLists.txt
  src/http/app_component.hpp
  src/oatppjsonapi.cc
Labels: build:compilation, process:ready-to-review, ci:skip-tests, process:merge-queued

#1437 feat: add crnn resnet native template
  src/CMakeLists.txt
  src/backends/torch/native/native_factory.cc
  src/backends/torch/native/native_factory.h
  src/backends/torch/native/templates/crnn.cc
  src/backends/torch/native/templates/crnn.hpp
  src/backends/torch/native/templates/crnn_head.cc
  src/backends/torch/native/templates/crnn_head.hpp
  src/backends/torch/torchinputconns.h
  src/backends/torch/torchlib.cc
  src/backends/torch/torchmodule.cc
  src/backends/torch/torchmodule.h
  src/dto/mllib.hpp
  tests/ut-torchapi.cc
Labels: kind:model, mllib:pytorch, process:ready-to-review, process:merge-queued
