Repository jolibrain/deepdetect, pull requests merged in 2023-03, with the labels that each got.

#1509 fix(api): re-add parameters in info call
  src/dto/info.hpp
  src/mlservice.h
  src/utils/oatpp.cc
  tests/ut-oatpp.cc
Labels: type:bug, kind:API, process:ready-to-review

#1510 fix(torch): when reading bbox dataset, also check that the class is n…
  src/backends/torch/torchdataset.cc
  src/backends/torch/torchinputconns.h
  src/backends/torch/torchlib.cc
Labels: datatype:images, mllib:pytorch, process:ready-to-review, process:merge-queued

#1511 fix(readme): correct docker tags for ci-master
  README.md
Labels: ci:skip-tests

#1512 chore: add function to convert tensor to images
  src/backends/torch/torchutils.cc
  src/backends/torch/torchutils.h
Labels: mllib:pytorch, process:ready-to-review, ci:skip-tests

#1508 feat(api): add labels in service info
  src/dto/info.hpp
  src/http/controller.hpp
  src/jsonapi.cc
  src/jsonapi.h
  src/mlservice.h
  tests/ut-oatpp.cc
  tests/ut-oatpp.h
Labels: kind:API, process:ready-to-review, process:merge-queued

#1515 feat(api): increase accepted header size
  src/http/app_component.hpp
Labels: process:ready-to-review, kind:httpserver

#1514 feat: add custom api path to swagger
  CMakeLists.txt
  docker/cpu-arm.Dockerfile
  docker/cpu.Dockerfile
  docker/gpu.Dockerfile
  docker/gpu_tensorrt.Dockerfile
  docker/start-dede.sh
  docs/docker.md
  src/http/swagger_component.hpp
  src/http/swagger_controller.hpp
  src/oatppjsonapi.cc
  src/oatppjsonapi.h
Labels: kind:API, kind:documentation, process:ready-to-review, ci:full-build, ci:docker

#1513 fix(torch): add measures to output event when training not done
  src/backends/torch/torchlib.cc
Labels: kind:API, mllib:pytorch, process:ready-to-review

#1516 chore: to libtorch2 and beyond
  CMakeLists.txt
Labels: mllib:pytorch, process:ready-to-review, ci:full-build
