Repository jolibrain/deepdetect, pull requests merged in 2023-02, with the labels that each got.

#1502 fix(trace_yolox): input shape for nonsquare images
  tools/torch/trace_yolox.py
Labels: process:ready-to-review, ci:skip-tests, process:merge-queued

#1504 fix: raise exception when a bbox file contains invalid classes
  src/backends/torch/torchdataset.cc
Labels: kind:connectors, datatype:images, mllib:pytorch, process:ready-to-review

#1505 fix(torch): small glitches in data augmentation
  src/backends/torch/torchdataaug.cc
Labels: datatype:images, mllib:pytorch, process:ready-to-review

#1503 chore: updgrade docker images to CUDA 11.8
  ci/devel-trt.Dockerfile
  ci/devel.Dockerfile
  docker/gpu.Dockerfile
  docs/source.md
Labels: kind:cuda, ci:full-build, ci:docker

#1506 feat(api): add a model_stats field containing the number of parameter…
  src/apidata.h
  src/backends/caffe/caffelib.cc
  src/backends/torch/torchgraphbackend.h
  src/backends/torch/torchlib.cc
  src/backends/torch/torchlib.h
  src/backends/torch/torchmodule.cc
  src/backends/torch/torchmodule.h
  src/dto/ddtypes.cc
  src/dto/ddtypes.hpp
  src/dto/info.hpp
  src/http/controller.hpp
  src/jsonapi.cc
  src/jsonapi.h
  src/mllibstrategy.h
  src/mlservice.h
  src/service_stats.cc
  src/service_stats.h
  src/services.h
  src/utils/oatpp.cc
  tests/ut-oatpp.cc
  tests/ut-oatpp.h
Labels: kind:API, process:ready-to-review, kind:dto
