Repository jolibrain/deepdetect, pull requests merged in 2023-01, with the labels that each got.

#1480 fix multi dim regression from images
  src/backends/torch/torchinputconns.cc
  src/backends/torch/torchlib.cc
  tests/ut-torchapi.cc
Labels: datatype:images, mllib:pytorch, process:ready-to-review, process:merge-queued

#1485 test(torch): add test for translation and bbox duplication
  tests/ut-torchapi.cc
Labels: process:ready-to-review, process:merge-queued

#1484 feat(regression): add l1 metric for regression
  docs/api.md
  src/supervisedoutputconnector.h
  tests/ut-torchapi.cc
Labels: process:ready-to-review, process:merge-queued

#1486 fix: take into account false negatives when computing average precision
  src/supervisedoutputconnector.h
  tests/ut-torchapi.cc
Labels: type:bug, mllib:pytorch, process:ready-to-review, process:merge-queued

#1489 fix(torch): correctly normalize l1 and l2 metrics for multi dim regression
  src/supervisedoutputconnector.h
Labels: type:bug, kind:connectors, process:ready-to-review

#1490 add percent error measure output for regression
  docs/api.md
  src/supervisedoutputconnector.h
  tests/ut-torchapi.cc
Labels: process:ready-to-review, process:merge-queued

#1491 fix(trace_yolox): make model autodetection work
  tools/torch/trace_yolox.py
Labels: kind:model, mllib:pytorch, process:ready-to-review, ci:skip-tests, process:merge-queued

#1488 feat(torch): add radam optimizer
  src/CMakeLists.txt
  src/backends/torch/optim/radam.cc
  src/backends/torch/optim/radam.h
  src/backends/torch/torchsolver.cc
  tests/ut-torchapi.cc
Labels: mllib:pytorch, kind:optimizers, process:ready-to-review, process:merge-queued

#1492 feat(torch): allow data augmentation to be only noise or distort
  src/backends/torch/torchlib.cc
Labels: datatype:images, mllib:pytorch, process:ready-to-review, ci:skip-tests, process:merge-queued

#1483 feat(trt): add int8 inference
  src/backends/tensorrt/tensorrtcalibrator.hpp
  src/backends/tensorrt/tensorrtinputconns.h
  src/backends/tensorrt/tensorrtlib.cc
  src/backends/tensorrt/tensorrtlib.h
  src/dto/mllib.hpp
  tests/ut-tensorrtapi.cc
Labels: mllib:tensorrt, process:ready-to-review, process:merge-queued

#1493 chore(torch): speedup dataset creation for bbox case
  src/backends/torch/torchdataset.cc
  src/backends/torch/torchinputconns.cc
Labels: mllib:pytorch, process:ready-to-review, process:merge-queued

#1495 chore(torch): speedup dataset creation for all image cases
  src/backends/torch/torchdataset.cc
  src/backends/torch/torchinputconns.cc
Labels: datatype:images, mllib:pytorch, process:ready-to-review, process:merge-queued

#1496 fix(torch): dataset size is half the database size
  src/backends/torch/torchdataset.cc
Labels: type:bug, mllib:pytorch, process:ready-to-review, process:merge-queued

#1498 fix(torch): avoid race condition when building alphabet
  src/backends/torch/torchdataset.cc
Labels: type:bug, mllib:pytorch, process:ready-to-review, process:merge-queued

#1497 feat(torch): data augmentation w/o db for bbox
  src/backends/torch/torchdataset.cc
  src/backends/torch/torchdataset.h
  tests/ut-torchapi.cc
Labels: mllib:pytorch, process:ready-to-review, process:merge-queued

#1499 feat: log model parameters and size at service startup
  src/backends/torch/torchlib.cc
  src/backends/torch/torchmodule.cc
  src/backends/torch/torchmodule.h
Labels: mllib:pytorch, process:ready-to-review, process:merge-queued

#1500 fix(torch): data augmentation handle dummy bboxes correctly
  src/backends/torch/torchdataset.cc
  tools/torch/trace_yolox.py
Labels: datatype:data augmentation, mllib:pytorch, process:ready-to-review, process:merge-queued

#1501 fix(trace_yolox): bbox shifted by 1 when training yolox
  tools/torch/trace_yolox.py
Labels: mllib:pytorch, process:ready-to-review, ci:skip-tests, process:merge-queued
