Repository jolibrain/deepdetect, pull requests merged in 2025-09, with the labels that each got.

#1598 feat: image padding with ratio conservation
  src/dto/input_connector.hpp
  src/imginputfileconn.h
  tests/ut-torchapi.cc
Labels: datatype:images

#1596 feat: update pytorch to 2.8.0
  CMakeLists.txt
  patches/pytorch/pytorch_280_fix_logging.patch
  patches/pytorch/pytorch_280_use_new_logger.patch
  src/CMakeLists.txt
  src/dto/common.hpp
Labels: ci:full-build

#1600 chore: prebuilt cache build instructions update
  ci/Jenkinsfile.prebuilt-cache
Labels: build:compilation
